### ISSUE TITLE
improve online visualization

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#101]
things that would be useful to see on every trial in the overview plot:
- title: mouse name, weight, date and time of session start
- subplot 1; something like current bars, division of trials into correct/error, contrast levels, total water
- subplot 2: single black psychometric function (will become 2 in biasedChoiceWorld)
- subplot 3: single black chronometric function (will become 2 in biasedChoiceWorld)
- subplot 4: tracking of variables that may trigger session end: running median RT, running average correct, or missed trials

When session ends, total duration and water intake should be saved to disk and potentially uploaded to FlatIron (partially redundant with the datajoint snapshots, but still good to have both)

**Comment by anne-urai** [comment]
it would also be nice to have the mouse name in large letters as a title for the online plot - so that during the task (with 3 rigs), the experimenter can quickly remember which animal is in which box

**Comment by anne-urai** [comment]
There could be a second set of subplots that is added after the session ends, shown to the experimenter, and saved to disk (and preferably uploaded to some common website).

It should show distributions of expected vs measured presentation times for sound and screen, ambient sensor, possibly a summary spectrogram of the microphone with some summary stats on the noise levels, etc.

**Comment by GaelleChapuis** [comment]
Is that envisionned @nbonacchi ?
