### ISSUE TITLE
fecal count - pop up window at end of session

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#103]
Fecal count: Could it be implemented as GUI pop-up at end of experiment (that can be cancelled)? (and can be saved into JSON field)

**Comment by nbonacchi** [comment]
what do you think about this:

task_settings.py will have a POOP_COUNT param set to True or False
if True it will ask the popp count and create the session with the weighing, water administration and poop_count.
If its False it will not do this but create the session anyway...
the POOP_COUNT var will be in the json dump of the metadata of the task and not searchable in Alyx.

This will also solve the problem of immediately creating a session after it is stopped so users can look at water delivered, weight, and manually add to Alyx's notes relevant notes about the session.

@oliche somthing like this:
```python
# Create conditional poop_count.flag from POOP_COUNT = True or False in task_settings
# Find poop_count.flags
# open settings file for session
# ask for poop count and update POOP_COUNT in settings dict
# save patched settings file
# delete poop_count.flag
finally (in separate call) 
# create session (this deletes the create_me.flag)
```
