### ISSUE TITLE
Flag - manually end of session or automatic

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#105]
When recording, we should not have automatic end of trial.

Can we create a flag so as to chose whether the session should be automatically ended or not?
Or will we have a different protocol entirely for physiology?

(we have now trainingchoiseworld, then biasedchoiseworld - then physiologychoiceworld ? )

**Comment by nbonacchi** [comment]
The recording protocol is the biased protocol.
As far as I'm aware the IBL is not (yet) doing learning.
After an animal is trained, the protocol is switched to biased, where there are no adaptive parameters and probabilities.

**Comment by GaelleChapuis** [comment]
But is there still in biasedChoiseWorld an 'automatic detection' of the end of session ?

With similar criterions as during the training (e.g. after 1h30, or if min trial reached in certain amount of time is too low)?

**Comment by GaelleChapuis** [comment]
Note: The program does not stop when the end of session is detected (at least during trainingChoiceWorld), so potentially we do not need a manual flag (the session can keep going even if the GUI window turns colored).

**Comment by nbonacchi** [comment]
biased has no automatic stopping criterions
