### ISSUE TITLE
Check minimum water value

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#107]
On 2018-10-22, it was agreed to use the following strategy to reduce water volume:

Proposal: Drop size starts at 3ul. Proposal : reduce by 0.1ul each day the mouse does >200 trials until minimum drop size is reached.

Min : 1.5 uL for sugar water, 2 uL for normal water

> Make sure the minimum value in the code is set at 1.5 uL

**Comment by nbonacchi** [comment]
This has been in production for a while. only difference is the min water, will set min value to 1.5 by default as the default of the water is:
```REWARD_TYPE = 'Water 10% Sucrose'  # Water, Water 10% Sucrose, Water 15% Sucrose, Water 2% Citric Acid (Guo et al.. PLoS One 2014)```
```python
ADAPTIVE_REWARD = True  # wether to increase reware at session start usin AR_* criteria
AR_INIT_VALUE = 3  # µl
AR_MIN_VALUE = 2  # µl
AR_STEP = 0.1  # µl
AR_CRIT = 200  # number of trials performed
```

**Comment by GaelleChapuis** [comment]
Could you add the comment :

`AR_STEP = 0.1  # µl - Min : 1.5 uL for sugar water, 2 uL for normal water`
