### ISSUE TITLE
Implementation of 'trained' criterion

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#108]
Note: 
- Data needs to be on same place, so as to look at 3 sessions back in time
- From 2019-01-21, enforcing animals to be trained in a single rig (unless debugging)

Deadline 10th Feb possible ?

**Comment by nbonacchi** [comment]
Number of sequential sessions to use: 3
Minimum # trials per session: 200
Minimum performance for performance on starting contrasts: 80%
Psychometric function to use with pooled trials: gamma + (1-2*gamma)* (erf( (contrast - threshold)/slope ) + 1)/2, where
Threshold: < 16
Slope: < 19
Gamma: < 0.2

**Comment by nbonacchi** [comment]
@GaelleChapuis I have a problem with this...
All analysis of behavioral indicators of subjects should be done outside of the rig. All adaptive protocol implementations until now only require me to load the last trial of the animal of the last session.

As I see it this is a convenience check for the users that will not allow you to run an animal that is trained in the trainingCW and vice versa, correct? (@anne-urai) 
For what I gather there is code that does this already using ONE and alyx queries ([here](https://github.com/int-brain-lab/analysis/blob/master/python/load_mouse_data.py) and [here](https://github.com/int-brain-lab/analysis/blob/master/python/is_learned.py)). Although the implementation could be improved, it makes little sense to me to re-select, re-download and re-fit data from an analysis pipeline every time I initiate a session. This is prone to more failures and will significantly increase the load time of the task. This analysis could also be done in datajoint so it would run automagically. We should have a way of simply determining if the animal is trained by having the analysis feedback to Alyx a boolean `isTrained=False | True` parameter in the subjects table.
@oliche @k1o0 @rossant what do you think?

**Comment by k1o0** [comment]
> All adaptive protocol implementations until now only require me to load the last trial of the animal of the last session.
But to clarify one of those parameters from the last trial is performance over the last 50 trials, correct? For the introduction on new contrasts we want the performance to carry over from the last session

**Comment by anne-urai** [comment]
I agree with @nbonacchi that Alyx could have a flag `is_trained` - if datajoint ingests are run daily (right now there's often a delay) we could run that through their pipeline and then write some info back to Alyx. Could pybpod then indicate that this flag is toggled to the user (e.g. throwing a warning when running a trained mouse on trainingChoiceWorld?

Another point is that we agreed that there should be two separate lapse rates, lambda and gamma, which should both be < 0.2 (so https://github.com/int-brain-lab/analysis/blob/master/python/is_learned.py is outdated). See https://docs.google.com/document/d/1fDJAeljJIYYYzL5Qloc9wfbsZYBlMy3h4nShcJSKCSo/edit

**Comment by nbonacchi** [comment]
@k1o0 yes yes... I save the current state of all buffers in all trials so last trial gives me all the info I need.

**Comment by GaelleChapuis** [comment]
@nbonacchi @k1o0 @oliche Please make sure this is followed up by the Database / DJ team if the decision is to compute the criterion in DJ and then input into Alyx.

We need this to happen soon for the Mice Training WG to function!

@nbonacchi I think the idea of Anne was great - indicate that this flag is toggled to the user (e.g. throwing a warning when running a trained mouse on trainingChoiceWorld).

**Comment by nbonacchi** [comment]
@GaelleChapuis sure, I can connect to Alyx and check the is_trained flag once it's implemented.
A couple of things are required for this to happen:
1. create the is_trained field in the subjects table
2. populate that field

For nº 1 it should be pretty easy to make. We talked about it in the last data meeting. @oliche is integrating it in the next Alyx release this coming Monday.

For nº 2 we can go the datajoint way or the one way.
Either way someone will have to write analysis code to process the required sessions and output a boolean value (I believe the Behavior WG already has code to do this). 
This value will then update the newly created field in the subject's table via rest query.
e.g. let's say subject IBL_11 has passed the criterions:
```python
one.alyx.rest('subjects/IBL_11', 'partial_update', data={'is_trained': True})
```
This will have to run every day against alive and untrained animals...

**Comment by nbonacchi** [comment]
The field could also not be a boolean but a text field or integer, I already saw a comment asking for a criterion to pass the animal from biased to ephys, so maybe 1 bit of info will not be enough

**Comment by GaelleChapuis** [comment]
@oliche  following today's meeting -- if you next 'fixtures' for the field, let me know.

**Comment by GaelleChapuis** [comment]
To follow-up : Is it decided whether the analysis to define if an animal has completed a certain protocol will emerge from DJ? As output, will a variable be changed into Alyx and used by pyBpod to indicate wether a mouse should go onto the next protocol?
In the case of the analysis passing through DJ, it is important to ensure that the data ingestion / analysis from DJ is working reliably.
