### ISSUE TITLE
Manage rig disk space by deleting old sessions

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblrig#113]
So maybe do 2 time frames
- a short one (2 weeks/ 1 months) for the video and audio raw files that take up a lot of space
- a longer one (6 months / 1 year) for the small behaviour sessions files

Probably need to make sure the data has been transferred and that the session has data registered on  on the flatiron by querying Alyx.

**Comment by nbonacchi** [comment]
We'll have to take care of all the video and audio data that yet needs to be compressed and uploaded

This has to ahppen BEFORE deleting anything !

**Comment by anne-urai** [comment]
One of our rig pc's is now full, so this is becoming  a bit more urgent. Would there be an easy way to check which videos are on flatiron and delete those?

**Comment by alejandropan** [comment]
Any news on this issue? Our rig computers are also getting filled up very quickly

**Comment by nbonacchi** [comment]
https://int-brain-lab.slack.com/archives/CEM70EXTN/p1553647732056400
