### ISSUE TITLE
fixed stimulus sequences during ephys

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#115]
Proposal for behavior during ephys
* There will be 10 unique pre-generated full-session stimulus sequences
* The sequences, consisting of stimulus contrasts and locations, will be used for all animals in for the official electrophysiology brain-wide activity map data set
* Sequences will be 2000 trials long, to ensure a large enough set of trials for a mouse to perform in a day
* Each sequence will cover one (recording) session and the set of sequences will be shuffled in blocks of 4 for each animal, aligned to the first day of ephys recording. This ensures that there is variation across animals, but that across sessions, all animals will have the same shared sequences (i.e. first 4 in random order, then second 4 in random order, etc). This will help comparison of data between different sites, when recorded in different animals.

Pre-generated sequence structure:
* First, a block with a 50/50 side balance to measure its unbiased psychometric function
* Contrast levels; -100, -25, -12.5, -6, 0, 6, 12.5, 25, 100
* 90 trials (10 per contrast level)
* Rather than randomly drawing from left/right on each trial, a perfectly balanced trial set will be generated and shuffled

Second, a sequence of blocks with 80:20 and 20:80 prior
* Block lengths will be drawn from an exponential distribution, truncated to between 20 and 100 trials.
* Contrast levels; -100, -25, -12.5, -6, 0, 6, 12.5, 25, 100, randomly drawn from uniform distribution (0% weighted 50%)
* Stimulus sides will be randomly drawn, with 20:80 or 80:20 probability depending on the block

**Comment by nbonacchi** [comment]
__Questions for the pre-generated sessions__:
    - mean of truncated exponential for block length == 60 trials? 
    - what about quiescence period + stimulus_phase vars, should these be fixed?


__ephysChocieWorld__ 
Will create:
 - 12 sessions instead of 10 (can divide by 4) ~2000 trials each I finish the block.
 - metadata in session file {'session_order': [1,2,3,4,8,7,6,5,9,10,11,12]} read from previous ephys session if exists

__session_creation__: 
    (5 contrasts * 10 trials - 5 trials pf "0") * 2 sides = 90 trials
    - create contrastLeft and contrastRight npy arrays (or one array in 2D) inside folder inside task folder
    [session_01.npy, ... session_12.npy]

   
__tasks_todo__:
    integrate sound board: installation + code w/ Filipe
    finish ephysCW code
    HW checks on rig: w/ Guido

**Comment by anne-urai** [comment]
`- mean of truncated exponential for block length == 60 trials?`: yes
`quiescence period`: varied from trial to trial, as in biasedChoiceWorld (can you remind me of the stats)?
`stimulus_phase vars`: not sure what that means

The rest sounds good

One additional request: can it be made clear (e.g. turn 'Run' button into 'Pause' or something) how we can hold trial presentation if the experimenter has to go in and adjust something?

**Comment by nbonacchi** [comment]
`QUIESCENT_PERIOD = 0.2  # + x, where x~exp(0.35), t ∈ 0.2 <= R <= 0.5`
stimulus_phase: the phase of the gabor patch relative to the center of the gaussian filter.

**Comment by anne-urai** [comment]
Without specification, everything should be kept the same as in `biasedChoiceWorld`

**Comment by nbonacchi** [comment]
Unless you guys forget something I guess...
I'm asking because it defeats the purpose of pre-generating sessions with fixed parameters.
