### ISSUE TITLE
make default flush_water time 24hours

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#116]
Make `valve_on_time` 60*60*24 so that it can be used for overnight flushing of ethanol (for cleaning)

**Comment by nbonacchi** [comment]
:) it's a bit much for a 60ml syringe no?

**Comment by anne-urai** [comment]
What's the current time for opening the valve? Flushing a 60mL syringe required 4-5 separate flush_water events. Could it be set to be a few hours to be sure it's up to the user to stop it (rather than come in the next morning and found that not all ethanol has flushed through)?

**Comment by nbonacchi** [comment]
Why has this been reopened?
#162 has more information on how to change the values of flush water for shorter or longer periods.

**Comment by anne-urai** [comment]
I know we can change the default, but that will reset with each update, no? So I'm requesting to change the flush_water to a longer value, at least long enough to allow a 60mL syringe to empty

**Comment by nbonacchi** [comment]
how longer? 3600 enough for you? 1 hour should be fine to flush the whole syringe.

**Comment by anne-urai** [comment]
Sure 1 hour is fine
