### ISSUE TITLE
Poop counter GUI not coming up

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#119]
At the end of the session no GUI comes up even though POOP_COUNT is set to True

**Comment by nbonacchi** [comment]
The poop counter window appearing is contingent on the poop_count.flag file being created.
This file is created with the create_me.flag file only if the session has more than 42 trials.
At the end of the session the task runs the poop_count command and the create session command always. however these commands will only do something if the flags are present.
