### ISSUE TITLE
Water calibration manual input of range doesn't work

### ISSUE THREAD

**Issue by valagui** [int-brain-lab/iblrig#125]
I'm trying to run the water calibration on one of the rigs with the new updated version of 3.7.1. The calibration runs fine, but it does not automatically use the scale even when the COM port has been entered and it does not give the option to input manual min or max ranges after the pop-up that indicates that the user is not done.

**Comment by GaelleChapuis** [comment]
Same issue in Berkeley - we ran the calibration just fine, the PDF popped up, but then there was no way to enter min / max value - should that be in the Anaconda prompt?
