### ISSUE TITLE
Bonsai shader window keeps on appearing on wrong screen

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#129]
At Berkeley, we setup the display as per the user guide.

It worked fine on one rig, but on the second (where there was apparently problems with the screen previously), the bonsai shader window which contains the stimuli keeps on appearing on the main PC screen.

After having dragged and dropped the bonsai shader from main PC screen to Ipad screen (using F11), and relaunching pybpod, the shader window still appears on the main PC screen

What to do?

**Comment by nbonacchi** [comment]
I believe we solved this previously.
Have you tried swapping the cables in the graphics card?

**Comment by GaelleChapuis** [comment]
We restarted the PC and kept the cable config as per the user guide and now it worked. Can close the issue sorry !
