### ISSUE TITLE
Save online GUI plots 

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#132]
Can we save the online plots (pybpod gui) after each session? This will serve as a sanity check.
This could be done locally on each Rig PC (i.e. it does not mean to be part of the general pipeline).

**Comment by nbonacchi** [comment]
Right now we cannot.
Given that there is going to be an overhaul of the visualization plots, we can implemented at that moment.

please keep in mind that at the end of the session the session is created in Alyx so performance, ntrials correct ntrials, task and water drank should be available immediately through Alyx.
Also the command prompt displays all this information after every trial. If it's just for immediate feedback users can check either the command prompt or Alyx.

**Comment by GaelleChapuis** [comment]
Sorry I am not sure if  your sentence 'Given that there is going to be an overhaul of the visualization plots, we can implemented at that moment.' means saving the GUI figure will be implemented eventually, or if it is impossible?

**Comment by nbonacchi** [comment]
I'm referring to issue #101 we should discuss there.
