### ISSUE TITLE
BUG - Data from behavioural plot dot not reflect mice performance - issue with data extraction or registration

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#133]
@nbonacchi Data from behavioural plots in DJ seem off - there seems to be an issue either in the data extraction or in the registration. Seems to happen following update version 3.7.0 .

Please check ??

**Comment by GaelleChapuis** [comment]
On that note, for later : it would be good to test the update before releasing it !

**Comment by GaelleChapuis** [comment]
Also related to Slack message here: https://int-brain-lab.slack.com/archives/C9L8DKZ9T/p1550166544020100

**Comment by nbonacchi** [comment]
There is a 2 day window from ver 3.7.0 to 3.7.1 where choice datasetTypes have a mistake. This is fixed now and since 3.7.1 the extractor should work properly.
The data will be patched but not immediately, we have to recursively re-extract all the sessions and warn datajoint to reingest.
