### ISSUE TITLE
habituation world - add basic GUI info

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#135]
If possible, it would be good to implement the GUI in Habituation world, displaying time elapsed, number of trial and water received.

**Comment by nbonacchi** [comment]
What is "the GUI"?
Is the information displayed on the prompt not enough?
Or do you want that in graphical form?

**Comment by GaelleChapuis** [comment]
![image](https://user-images.githubusercontent.com/43007596/53040686-d8b30500-3436-11e9-862e-b643efa5f933.png)
GUI > Talking about Figure 1.

**Comment by GaelleChapuis** [comment]
Ah sorry we missed the prompt !
Information in the terminal is enough, thanks @nbonacchi ! Closing the issue.
