### ISSUE TITLE
Could not find data on BNC2

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#140]
After latest upgrade I have issue with the audio amplifier in rig2 , it does not see inputs. I have checked cables they are fine. Before upgrade to latest version there was no issue with this.

**Comment by nbonacchi** [comment]
That's strange, nothing was changed from the previous version to this version in terms of sound it might be another type of issue?

**Comment by karolinasocha** [comment]
I just plug and unplug out cables and finally it worked.
