### ISSUE TITLE
shader window from the behaviour camera appears on ipad screen

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#141]
I have this issue on two rigs that shader window edge appears on ipad screen. I tried to changed location of the camera window but does not remember previous settings. I turn off ipad screen , unplug cable from adafruit board, unplug DP cable from the computer but the issue stays. It is on two rigs.

**Comment by nbonacchi** [comment]
the shader window is the stimulus, it should appear on the iPad screen, do you mean the camera display window?

In C:\iblrig\camera\camera_recordings\one_camera_bonsai.layout (line 19 to 28 should read):
```
<DialogSettings>
    <Visible>true</Visible>
    <Location>
      <X>678</X>
      <Y>65</Y>
    </Location>
    <Size>
      <Width>445</Width>
      <Height>355</Height>
    </Size>
```
unless you have a screen resolution of less than 1123 (which hopefully you shouldn't) which is 678 + 445 (X + Width) the camera dialog should be fully inside the PC screen

What's the resolution of your screen? try increasing the resolution of your PC screen

Another possible fix is to switch the side of the screen i.e. If you right click on Desktop and select Display settings, the iPad screen is either on the left or on the right of the main screen, switching the sides will make the camera display overflow on the other side.

**Comment by karolinasocha** [comment]
Thanks! I have change X-value:  <X> 478 and it is not displayed on the ipad screen anymore.
