### ISSUE TITLE
Could not find signal on BNC1

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#142]
Rig 1 issue: the photodiode , F2TTL , ipad screen , adafruit board, pybod works. I have checked every part on working rig and it did not give any error. Only in rig 1 bpod cannot detect signal from the screen (BNC1 input). Any ideas?

**Comment by nbonacchi** [comment]
As for sound (#140) no changes were made in any of the logic pertaining the photo-diode.
If it was working prior, try disconnecting and reconnecting the USB cables from the computers on the rigs where you have problems, this should reset the boards of the modules... Then you can test things using a random protocol. I like to use the habituation protocol as it has sound cameras visual stims and vale openings and it elapses trials automatically.

If that fails try rebooting your machine, Windows may have updated during the night or something...

**Comment by karolinasocha** [comment]
The intensity of the  screen that has this issue is 60 lux. In other rigs the intensity is higher (rig2 =89 lux; rig3=85). So that is potential issue of lack of detected pulses;
