### ISSUE TITLE
Display temperature value during the task

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#143]
Could we plot on the online GUI Figure 1 the temperature / humidity at each 20s of trials, in black as default, and in red if outside of this range:

from Jax: Temperatures of 65-75°F (~18-23°C) with 40-60% humidity are recommended
(note that accuracy of humidity sensor is +/-3%).

If not on the GUI, on the prompt?

 And if too much processing is needed to plot online, just plot the first and last trial value on the prompt.

@anne-urai does that seem reasonable to you?

**Comment by nbonacchi** [comment]
Both prompt and GUI are possible.

Do you want this independently of saving the data?
Meaning, should this be displayed even if **RECORD_AMBIENT_SENSOR_DATA** in task_setting is set to `False`?

**Comment by GaelleChapuis** [comment]
Yes, I would say display even is variable set to `False`.

@anne-urai as a user, what do you think of this question: Would it be worth writing in parenthesis (Rec) or (-) if **RECORD_AMBIENT_SENSOR_DATA** in task_setting is set to `True` or `False` repectively ?

**Comment by anne-urai** [comment]
I think plotting data implies that these data are saved - so if the sensor is connected but set to False, I think plotting it gives the false impression that these data are saved (and if the sensor works there is really no reason to not save the data since it's small). So my vote would be to only display when saving.

**Comment by GaelleChapuis** [comment]
Ok  - @nbonacchi Please implement the data writing (on the GUI) only is variable set to `True`.
