### ISSUE TITLE
unselect subject checkbox at start of task

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#148]
When starting a new task, the previous subject is still selected in the tickbox. This can lead to mistakes when the experimenter forgets to untick the previous subject, causing the next animal to run under the previous animal's name. To avoid confusion, and throw a warning when running a task without a subject, the box should be unticked by default.

**Comment by nbonacchi** [comment]
Hummm
I con look into this to see if it's possible to run a script at the endof any task that removes any subjects from the current setup, or all setups by talking to the pybpod API... This also will mean that if you press start and stop or something goes wrong and the task bugs out, the subject will have to be reintroduced manually. I am worried that this will become another annoying feature like the save before run that we're fixing now, what do you think?

**Comment by anne-urai** [comment]
I think it's better to have to re-select in case of a (rare) crash, then to run the risk of accidentally running with the previous subject selected (which has happened a few times already).

**Comment by nbonacchi** [comment]
we're fixing the mouse interface for running the task, that should solve the problem, you'll be able to use that interface as you were doing before, it should come out when pybpod is updated.
