### ISSUE TITLE
Subject: doesn't exist in Alyx

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#155]
I connect with cortexlab alys to load mice in IBL python rig. However in the end of the session I have error message that Subject does not exist in alyx. 

It connected to https://alyx.internationalbrainlab.org in the end of the session. 
So it seems that it does not save my previous settings to connect to alyx.cortexlab.ne

```

Connected to https://alyx.internationalbrainlab.org as Karolina_Socha
2019-03-11 19:32:48.969 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\KS002\2019-03-11\001
2019-03-11 19:32:49.18 ERROR    [registration.py:50] Subject: KS002 doesn't exist in Alyx

```

**Comment by oliche** [comment]
So those scripts depend on ibllib, the parameters are in the .one_params file, could you pease check it ?

Location of the file depends on your OS and is described here:
https://ibllib.readthedocs.io/en/develop/03a_installation_matlab.html?highlight=.one_params
