### ISSUE TITLE
proportion of correct trials plot during behaviour training

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#164]
Is the plot of proportion of correct trials correct? There is more error trials than correct but on the plot on the bottomthe proportion is near 1.

![image](https://user-images.githubusercontent.com/32096962/54448631-1c521380-4744-11e9-8263-d7cdec3a3974.png)

**Comment by nbonacchi** [comment]
This is actually correct
the proportion of correct trials ignores the repeated trials. It's just the number of correct tirials overall / by the number of non repeated trials...  
This animal is probably doing a win-stay loose-switch strategy? Or maybe paying attention to the stim once and that repeating the same action... I'm not sure... Maybe some strategy analysis of how subjects learn is warranted.
Also maybe I can change this to be only the performance of adaptive trials?
