### ISSUE TITLE
wait for mouse to be headfixed before starting task

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#165]
After running a behavioral task and logging the mouse's weight, it would be great if the video could start, but trial presentation is paused until the user confirms 'the mouse is correctly positioned and the box is closed' - could a confirmation dialog box be added between the video screen start and trial presentation?

**Comment by anne-urai** [comment]
Use case: if I accidentally press enter after entering the weight, the task starts before the mouse is headfixed

**Comment by nbonacchi** [comment]
The video must be launched by the first state after the state machine starts or the timestamps will be useless for synchronization purposes.
If your concern is with the camera positioning, the best would be to do this sans mouse but maybe you can switch the order of doing things if you need the mouse inside? 
If the background is gray, there is no change in the visual field of the mouse when you start the visual stimulus. So after knowing the weight and head fixing the mouse, you could check using the flycap software or the camera alignment software before running the task. Once everything looks OK, close everything and launch the task, insert the weight and press OK.
