### ISSUE TITLE
GUI change colour when 90 minutes is reached in rig

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#166]
As an 'end of session' criterion, the Mice Training WG needs to add a criterion:
- if the mouse is in the task for 90 minutes (but not disengaged), the GUI needs to change colour. (the task is not stopped, in case the user wants to train for longer)

**Comment by nbonacchi** [comment]
Now we have:
- Plot background color change to **green** if < than 400 trials in 45 minutes
- Plot background color change to **yellow** if Median response time of latest N = 20 trials > than 5 times the median response time and more than 400 trials performed
I can introduce:
-  Plot background color change to **red** if 90 minutes have passed?

**Comment by GaelleChapuis** [comment]
Alright !  (but not too super-bright)
