### ISSUE TITLE
training Choice World stopped

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#167]
During session with training Choice World after 23 minutes everything has frozen: stimulus screen, recording trials etc. After stopping and then stopping trial nothing has changed. There was no response from software.
There was no message error in window prompt. 
The session has been closed manually.

**Comment by valagui** [comment]
This is also happening here at CSHL on two of our rigs

**Comment by karolinasocha** [comment]
So it is incidental error? Do you start training again ?

**Comment by valagui** [comment]
I believe so, if my mouse has only been training for a few minutes I just re-start everything from closing the command window and all accompanying windows.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Tue, Mar 19, 2019 at 4:50 PM -0400, "karolinasocha" <notifications@github.com<mailto:notifications@github.com>> wrote:


So it is incidental error? Do you start training again ?

**Comment by nbonacchi** [comment]
Closing everything is good,

Has anyone noticed if closing pybpod between sessions minimizes this happening?

**Comment by valagui** [comment]
I have after re-starting it does happen less.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Wed, Mar 20, 2019 at 6:07 AM -0400, "Niccolò Bonacchi" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing everything is good,

Has anyone noticed if closing pybpod between sessions minimizes this happening?

**Comment by karolinasocha** [comment]
Yes it does. I always launch pybpod for each session.
