### ISSUE TITLE
changing position and size of pyBpod window

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#171]
Sorry for bothering again but I cannot find where I could change position and size of the main window of pyBpod (picture below)? Everytime when I launch pyBpod some part goes to ipad screen.

![image](https://user-images.githubusercontent.com/32096962/54707835-e9d85a00-4b39-11e9-8c74-d122cd71d698.png)

**Comment by nbonacchi** [comment]
That is probably somewhere in the site-packages folder of the environment. It's a QT window and I don't thing the main window has a particular position configured, it probably has a size configured though. This means that where it appears is controlled at the level of the window manger of the OS.
The positioning of all windows of on the rig assume a horizontal screen.
