### ISSUE TITLE
suggestions for online visualization improvement

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#175]
**The current online visualization is quite useful (especially chronometric and psychometric functions), but can be improved in several ways to be more legible**
![img_20190328_144609 648](https://user-images.githubusercontent.com/6636245/55195646-a73eff00-5183-11e9-8fcf-cfa2dd46a69c.jpg)

Proposed improvements:
* remove legend from first subplots, hides the bars with values
* move subplot on bottom right to top right, same layout as top left (y-axis has text description, then bars with values written). The values will help interpret the units, which now (e.g. for humidity? and the blue/pink bars which don't even have a legend) are unclear.
* remove legends from psycho/chronometric function, and color the blocks the same way as the snapshots (black = 50/50, red/orange = leftProb20, blue/green=leftProb80)
* at the start of the session, initialize unused datapoints as NaN rather than zero - so that it doesn't look like e.g. the psychometric function has only 'left' choices for contrasts that are not in the set or haven't been presented yet.
* add axes labels to psychometric and chronometric functions
* remove seconds from title, too detailed

**Comment by nbonacchi** [comment]
If you increase the window size you'll see all the legends...

It's a good idea of putting all bars in the same direction in the same plots, I'll see what I can do for one of the next releases.

btw the plot will save with the size it has in the last trial so if it's small and the legends cover the plots you'll not be able to see more after the fact.

Regarding colors: 
black at alpha=0.5 for 50/50, check
red/orange for left prob low, red or orange?
blue/green for left prob high, same question blue or green?

**Comment by anne-urai** [comment]
Since it's quite a hassle to perfectly resize the plot on every session (and we need to keep screen space for the video and conda prompt, I propose making it legible in the size that it starts in rather than requiring the user to resize! Removing the legends and putting them in the y-label, as in the first subplot, would go a long way (and the font size could also decrease a bit).

Colors for biasedChoiceWorld:
0.7634747 , 0.33484566, 0.2258923 for leftProb_low
0.133, 0.133, 0.133 for neutral
0.24715576, 0.49918708, 0.57655991 for leftProb_high

Note that the direction of the shift of the psychometric function depends on how you code the signedContrast and responses. I take the x-axis as (contrastRight-contrastLeft) * 100 and the y-axis as df['choice'] = -1*df['choice'] (so that it means the perceptual interpretation, rather the motor output, of the animal).

I know you don't fully agree with this interpretation, but for comparability with the snapshots it would be great if we could use the same convention!
![Screen Shot 2019-03-29 at 07 57 40](https://user-images.githubusercontent.com/6636245/55231232-5c130380-51f8-11e9-8e69-dc732f1e383e.png)

[biased_blocks_summary.pdf](https://github.com/int-brain-lab/iblrig/files/3022513/biased_blocks_summary.pdf)
