### ISSUE TITLE
camera bug after update to v4.0.0

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#179]
**Describe the bug**
In the Carandini Lab, on all 3 behaviour rig, after update to v4.0.0, camera synchs are bugging.
Changes are made to the camera settings manually in the flycap software. Settings are : 10 framerate, unclick ON/OFF, 2) trigger/strobe > enanable/disable trigger set as 'ticked'

**To Reproduce**
1. Change settings in flycap
2. Click on pybpod
3. See error occuring in terminal: no pulse on port 1
4. Visual stimulus then freezes after launching the session.

This error does not occur all the time on launching, but on almost every sessions.

**Comment by nbonacchi** [comment]
Not sure I understand the bug. No camera syncs are recognized?
Is this regarding 4.0.0 or 4.0.1?
Frame rate checkbox should be on and frame rate set @ 30.016fps (set it to 30 it should auto correct).
