### ISSUE TITLE
constant issues with camera pulses and stimulus sync; freezing: stimulus and camera window

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#181]
Every time when I launch new session I have issues with camera pulse synchronization and additionally to that I have now also issue with screen pulses. Then I double checked camfly2 and settings however I had still issues:

I launch again new session and at the beginning of the session visual stimulation freezes and gives error regarding to vistim sync pulses and then again camera pulses.

**To Reproduce**
```

inding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
08/04/2019 03:51:47 | WARNING | 7064 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
libpng warning: iCCP: known incorrect sRGB profile
2019-04-08 15:52:08.842 INFO     [session_params.py:204]
##########################################
PREVIOUS SESSION FOUND
LOADING PARAMETERS FROM: C:\iblrig_data\Subjects\KS003\2019-04-05\002\raw_behavior_data\_iblrig_taskData.raw.jsonable

PREVIOUS NTRIALS:              500
PREVIOUS NTRIALS (no repeats): 469
PREVIOUS WATER DRANK: 922.4999999999999
LAST REWARD:                   2.4999999999999996
LAST GAIN:                     4.0
LAST CONTRAST SET:             [1.0, 0.25, 0.125, 0.0625, 0.0]
BUFFERS:                       loaded
PREVIOUS WEIGHT:               26.4
##########################################
2019-04-08 15:52:08.843 INFO     [session_params.py:215]
##########################################
ADAPTIVE VALUES FOR CURRENT SESSION

REWARD AMOUNT:      2.5999999999999996 µl
VALVE OPEN TIME:    0.044 sec
GAIN:               4.0 azimuth_degree/mm
IMPULSIVE CONTROL   OFF
##########################################
2019-04-08 15:52:10.631 INFO     [_iblrig_tasks_trainingChoiceWorld.py:90] Starting trial: 1
2019-04-08 15:52:12.825 INFO     [trial_params.py:389]
##########################################
TRIAL NUM:            1
STIM POSITION:        -35
STIM CONTRAST:        0.0625
STIM PHASE:           0.0
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.38639999999999997

TRIAL CORRECT:        True

NTRIALS CORRECT:      1
NTRIALS ERROR:        0
WATER DELIVERED:      2.6 µl
TIME FROM START:      0:00:13.810064
TEMPERATURE:          23.93000030517578 ºC
AIR PRESSURE:         1007.22998046875 mb
RELATIVE HUMIDITY:    48.865234375 %
##########################################
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2019-04-08 15:52:13.127 WARNING  [check_sync_pulses.py:37]
        ##########################################
                NOT FOUND: SYNC PULSES
        ##########################################
        VISUAL STIMULUS SYNC: COULD NOT FIND DATA ON BNC1
        SOUND SYNC: OK
        CAMERA SYNC: COULD NOT FIND DATA ON Port1
        ##########################################

TRIAL CORRECT:        True

```

After restarting and loading pyBpod ports I had still error with screen pulses, camera preview freezes, stimulus appeared on the screen. 

![image](https://user-images.githubusercontent.com/32096962/55734106-e2a8bb80-5a16-11e9-8aae-c94c17fc2998.png)

**Comment by nbonacchi** [comment]
This on all the rigs?

**Comment by karolinasocha** [comment]
Rig3 - had these issues today. The freezing stimulus happend also on rig 2 today, but then after restarting and checking camera settings I could start session without issues with sync pulses (only first trial showed that camera pulses are not detected but next trials were fine). On rig1 as standard there was issue with camera pulses but then I again check settings in capfly2 and run session without troubles (also at the first trial there was error that pulses from camera are not detected). 
Now I restarted on rig3 pybpod and checked capfly2 settings again and started session. However I have issue with screen pulses sync. 

I run only trainingChoiceWorld protocol in all of these rigs.

The issue with camera pulses (that it is not detected) happens everytime, in all my rigs, when I start training session. It seems it does not remember the settings in capfly2 or settings in capfly2 are somehow changed. 

Issues on rig3 are new. Last training was on Friday (no issues with screen pulses). During the weekend I have not trained animals and did not touch rig. Now it does not detect screen pulses in that rig.

**Comment by nbonacchi** [comment]
The issue with FlyCap2 not remembering the settings I think happened to me also...
Bonsai now will toggle the trigger mode, menaing that if it is on it will turn it off at the beginning and on at the end of the Bonsai workflow. This also means that if it is off it will turn it ON...
I solved it by turning everything of, setting the Camera config as I wanted (if you find a button to save configurations save them) then closing flycap. Then I opened a new Bonsai workflow, added a FlyCapture input node, right click on the node and select image from the output, then running the workflow and double clicking on the image node to see the camera output. If the camera output shouws a white scerrn it means that the toggle has been saved. 

On random freezes of the stimulus, it might be that the command prompt is acting out. if you right click on the command prompt there is an options tab, if you unclick quick edit the issues seem to at least reduce. Whenever pybpod freezes usually just clicking on the command prompt and pressing enter works for me. It seems that the console is very sensitive about doing other things during sessions, we should minimize any extra task activities, i.e., no slack, no e-mail, etc...

About sync pulses, I believe it's not a software issue but a hardware one, if properly set up the sync pulses should be detected, if not we have to figure out what is failing.

On github issues, I appreciate you taking the time to describe the problem in as much detail as you can, like what you did here :) In the future it would be better to open one issue per, well... issue, so for example this issue should be 3 issues at leaset, one on sync pulses, one on freezing, one on camera configuration. I know it's a bit of a hassle but it helps with managing what was fixed when or even if a bug is a bug or a random event. If you want a more colloquial interaction Slack-me and we can chat either DM or on the #data-python-rig-dev or in the #troubleshooting channel.
