### ISSUE TITLE
smaller sync square

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#184]
The current frame2TTL clip does not cover the whole sync square, so the flicker is visible to the animal. 
![img_20190411_171521 269](https://user-images.githubusercontent.com/6636245/56002771-9e751f80-5c91-11e9-9e87-b8907433f9a1.jpg)

Could the sync square be either made smaller to fit within the clip size (both when clipped horizontal and vertical, or a user-defined number of pixels so it can be adjusted per rig?

**Comment by nbonacchi** [comment]
The sync square size can be controlled using the variables:
```python
SYNC_SQUARE_X = 0.95
SYNC_SQUARE_Y = 0.17
```
from task settings in each task that uses visual stimuli

**Comment by anne-urai** [comment]
feature request (non-urgent): can this become a shared variable between all tasks, so that the software setup can include adjusting the size without having to do that separately for each task? 

Related to #52 - perhaps in the screen calibration, the user can check that the square is small enough to be covered by the clip but big enough to trigger TTLs

**Comment by nbonacchi** [comment]
Quick solution for now given that all rigs are identical is for someone to give me the new default values. I can change them for every task.

**Comment by anne-urai** [comment]
Suggested new defaults: X = 1.33, Y = -1.03
