### ISSUE TITLE
cannot transfer data from rig1 to globus folder; no registration file 

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#190]
I cannot transfer data in globus, after training session, there is no registration file. I am not sure if the error that occured during starting the training session is related to that issue (rig1; for trainingChoiceWorld):

```
Finding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
05/05/2019 08:18:24 | WARNING | 5196 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
libpng warning: iCCP: known incorrect sRGB profile
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```
Then, after training session there is no registration file in the folder.
So I have re-installed ibllib but then again at the beginning of the training session I had this error:
```
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```
An in the end this error|:
```
Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
```
And there was no transfer file in the folder:
![image](https://user-images.githubusercontent.com/32096962/57199314-6baf0600-6f75-11e9-9991-153cdadf0027.png)

I re-installed ibllib following these steps:
1. I renamed old folder ibllib to ibllib_archieve
then in cmd prompt I followed these steps
(https://ibllib.readthedocs.io/en/latest/02a_installation_python.html):
2. git clone https://github.com/int-brain-lab/ibllib.git
3. conda create -n ibllibenv
conda activate ibllibenv
conda install -c conda-forge ciso8601
4. cd ibllib/python
pip install -r requirements.txt
pip install -e .

**Comment by nbonacchi** [comment]
ibllib is installed by the rig code, you do not need to install ibllib by itself on the rigs, the only python environment on the rigs should be iblenv which is built and updated by install.py and update.py
Except in very rare occasions or if you're setting up a rig from scratch, you shouldn't have to ever manually install anything on the rigs. The instructions you followed for ibllib are to install ibllib by itself in dev mode, please roll back these changes.

All the error messages you mention are not errors just warnings and can be ignored...
the flag file is created if the session has more than 42 trials, does this session have more than 42 trials?

**Comment by karolinasocha** [comment]
Thank you for this. I was checking the rig yesterday to double check if after update there is any issue. Indeed, there was no 42 trials.
