### ISSUE TITLE
Excessive water during biasedCW

### ISSUE THREAD

**Issue by njmiska** [int-brain-lab/iblrig#196]
I started a mouse in biasedCW, and each reward delivery was 3uL.  The animal was given 1.5mL within 600 trials (~40mins), and was already satiated at that point.  Reward amount needs to be far lower so that animals do more trials.  According to Nicco, "the default in task_settings of the biasedCW is 3µl, it's a parameter that is fixed for the whole session and user defined".  Reward amounts should be much smaller, either 1.5uL or 1.5uL x some small scaling factor related to animal weight.  See slack thread: https://int-brain-lab.slack.com/archives/C8Q01DNN4/p1559730909023800

**Comment by GaelleChapuis** [comment]
@nbonacchi the bug might have occurred from the transition from trainingChoiceWorld to biasChoiceWorld.

Does the software check for the reward value that was used in the previous session in biasChoiceWorld?

**Comment by nbonacchi** [comment]
trainingCW is the only task that overrides the parameters in task_settings depending on the animal's performance in previous sessions. So, biasedCW runs the IBL task with the values that are set and modifiable in task_settings.py
I can change the default to 1.5µl but people have to start checking the parameters before running the tasks.

**Comment by njmiska** [comment]
Ah I see, I didn't realize that this was something we should be changing?  That will fix the problem for me for now (I'll just manually change it to 1.5uL).  However, we may want to change this going forward such that it scales with an animal's initial or current weight (what we are currently discussing on slack)
