### ISSUE TITLE
To add - New criteria for disengagement

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#203]
New criteria for disengagement: 1) the mouse has not done 400 trials in 45 minutes AND 2) the mouse has not done 45 trials in the last 5 minutes

In other terms :
after 45 minutes check how many trials the mice has done. If it hasn't done 400 trials in total or 45 in the last 5 minutes (from the 45 minute moment) the disengagement criterium is triggered

**Comment by GaelleChapuis** [comment]
(to be verified if OR or AND, please do not implement just yet)

**Comment by nbonacchi** [comment]
**_Approved stopping criteria_**
1 - Less than 400 trials in 45 minutes
2 - Median response time of latest N = 20 trials > than 5 times the median response time of whole session AND more than 400 trials performed (no time criteria)
3 - 90 minutes elapsed since session start

All these are independent from each other and the first one is already implemented.
You want me to add:
4 - 45 minutes elapsed AND less than 45 trials in 5 minutes

**Comment by GaelleChapuis** [comment]
I would say 4- is correct, awaiting for Guido to confirm.

**Comment by k1o0** [comment]
New training criterion:
The mouse completes over 400 trials and its performance over the last 50 easy trials drops below 40% of its performance over the entire session.  For example if it had been performing at 90% for the easy trials over the session, this criterion would activate if over the previous 50 trials the performance was < 60%.

```
So for the training protocol: 
Maximum session length in minutes: 90 if # trials > 400 else 45
Session also ended after minimum of 45 min if < 45 trials in last 5 min.
Criteria when # trials > 400:
  1. Threshold reaction time increase: 5 x session median
      # trials over which to compare median reaction time: 20
  2. Threshold performance decrease (easy trials): 40% of session average
      # trials over which to compare average performance: 50
```

Here's the code I used for this criterion through DataJoint:
https://github.com/int-brain-lab/analysis/blob/4dfe40589d80cf93b09f67b22d0919cc04cea3c4/python/end_session_criteria.py#L37-L48

**Comment by GaelleChapuis** [comment]
@nbonacchi is it now implemented in the pyBpod tasks?

**Comment by GaelleChapuis** [comment]
As it was never implemented, but remains a good idea, we can close it but add a tag "idea4later" so it's easily searchable for in the future.

**Comment by anne-urai** [comment]
I propose to close this for now, as we're resubmitting a paper with the old criteria described in detail.
