### ISSUE TITLE
Add A-P, M-L, D-V at probe location input

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblrig#213]
Now the location of the probe is put in using X, Y, Z and D. It would be nice to add the axis names, for example: 
X (M-L): 
Y (A-P): 
Z (D-V): 
D (Depth):

**Comment by oliche** [comment]
And directions. In Needle we use:
Left+, Right-
A+, P-
D- V+

Reminder: right hand, index forward middle finger towards center of Earth will give you directions

**Comment by anne-urai** [comment]
I propose using the Sensapex standard (have to check what it is) to more easily read off the values from the manipulator. Note that their displays are by default in microns instead of mm, so the units would also be nice to add to the pop-up window.

**Comment by guidomeijer** [comment]
I would argue against that. If we use the Sensapex standard it might be easier for us to input the values but not easy for the rest of the world the figure out what we did. Inputting the values in microns because that's what Sensapex shows is fine by me. But I think we should attribute plus and minus not according to Sensapex standards.

In the ephys meeting it was brought up that the convention is: Left: -, Right: +. So the reminder is to use your left hand instead of your right.

I would propose the following names at the pop-up box:

M-L (X): [textbox] μm
A-P (Y): [textbox] μm
D-V (Z): [textbox] μm
Depth:   [textbox] μm

Sign: -left, +right, +A, -P, -D, +V
