### ISSUE TITLE
Circular stimulus artifact

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblrig#215]
A darker grey circle appears after each trial and during zero contrast trials that moves as the normal stimuli do, creating an opportunity for mice to perform above chance on zero contrast trials

**To Reproduce**
1. Run BiasChoiceWorld as test user
2. Perform trials until zero contrast trials occur

**Expected behavior**
No stimuli whatsoever between trials and during zero contrast

**Comment by GaelleChapuis** [comment]
Idea: instead of even displaying a stimulus, do not display anything (i.e. show grey screen, no close-loop) - this will avoid any issue with the shader configuration.

Note: calibrating screen should make the stimulus artefact disappear for now.

**Comment by GaelleChapuis** [comment]
Check that once a stimulus is on center, and disappears, no black circle is seen.
