### ISSUE TITLE
Purge script should have a confirm button 

### ISSUE THREAD

**Issue by valagui** [int-brain-lab/iblrig#216]
**Is your feature request related to a problem? Please describe.**
I accidentally ran the purge script by accident (it looked like the transfer raw data one), so I think it would be wise to add a confirmation prompt in order to prevent accidents. 

**Describe the solution you'd like**
Perhaps adding a y/n option as with the update. 

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by nbonacchi** [comment]
The purge script only deletes data that is found on Flatiron but you have to give it the iblrig_data folder location and the filename you want to delete.
The transfer function already deletes the video and audio after it being transferred to the local server, so you shouldn't be needing the purge script on a regular basis. If you have a shortcut for it it's probably overkill, especially if you think you might make mistakes. I'd suggest removing the shortcut and running the command when and if you need it. Instructions on how to run this can be found on the second page under nuber 3) in this doc: https://docs.google.com/document/d/1vvHYHJiTgYPepoLbPIaUbrUWd9VO8g_JliMFUtfZeYs/edit#heading=h.u9nhq8ibi95v
