### ISSUE TITLE
'XONAR SOUND CARD(64)' IndexError: list index out of range

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#217]
I got an error message regarding Sound Card in my ephys behavior computer. 

I have the latest version of pyBpod (5.2.3) and installed a sound card; then I tried to test habituationChoiceWorld protocol but received this error message. 

```
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 19, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\session_params.py", line 88, in __init__
    output=self.SOFT_SOUND, samplerate=self.SOUND_SAMPLE_FREQ)
  File "c:\iblrig\iblrig\sound.py", line 37, in configure_sounddevice
    devices) if 'XONAR SOUND CARD(64)' in d['name']][0][0]
IndexError: list index out of range

```

**Comment by anne-urai** [comment]
For the ephys behavior PC (assuming you have the CCU soundcard, and *not* the Xonar) the `SOFT_SOUND` should be `None` instead of `'xonar'`

**Comment by karolinasocha** [comment]
I changed that in iblrig and iblrig_params; 
It seems that does not detect connection through USB port. 
There are two USB cables from SoundCard (micro and mini). 
I can see the connection from mini USB (and I wrote that number of COM for SoundCard settings) but I do not see any COM related to micro USB. I plugged and unplugged USB cable but still having the same error.

```

Unable to connect to the Sound Card through the USB port. You will be unable to send and receive sounds.
2019-07-25 16:58:41.323 ERROR    [sound.py:206]
   ##########################################
   SOUND BOARD NOT FOUND ON SYSTEM!!",
   PLEASE GO TO:
   iblrig_params/IBL/tasks/_iblrig_tasks_habituationChoiceWorld/task_settings.py
   and set
       SOFT_SOUND = 'sysdefault' or 'xonar'
   ##########################################
Traceback (most recent call last):
 File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 19, in <module>
   sph = SessionParamHandler(task_settings, user_settings)
 File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\session_params.py", line 93, in __init__
   self = sound.init_sounds(self, noise=False)
 File "c:\iblrig\iblrig\sound.py", line 207, in init_sounds
   raise(NameError)
NameError
```

**Comment by guidomeijer** [comment]
In that case repeat step 2.2 of the setup guide: https://docs.google.com/document/d/1z_xiQl-AqLZwJdVwjOzn46LoK80R9EU3JIrVkFk9JgU/edit

**Comment by karolinasocha** [comment]
This is solved, I did that installation regarding that document but there were additional steps to do. I am going to write what I did so anyone that has this issue can quickly solve it. The first step is to change Sound Card settings in "task_settings" files in iblrig folder and iblrig_params folder. Secondly, you should open Zadig and then run pyBpod (at least it did not work for me and could not detect Harp Sound Card in pyBpod) and thirdly before running the task make sure that you have connected sound card (in pyBpod:  tools-->sound card--> Harp Sound Card and connect).
