### ISSUE TITLE
Possibility to input coordinates of probes after recording

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblrig#218]
For each probe it would be good to have the option to say "I will input the coordinates after the recording". One might forget to zero on bregma, or sometimes it's not possible to reach bregma because another probe has already been inserted in the brain and is blocking the way. Then when checking this option, pybpod opens the probe coordinates again after the task and the user can backtrack to bregma after taking the probe out.

**Comment by nbonacchi** [comment]
Can add a tool that just launches the probe GUI and patches the settings file.
This will have to run before transfer, probably default to the latest ephys recording asking confirmation to the user
