### ISSUE TITLE
warn the user when trying to run biasedChoiceWorld before mouse is trained

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#221]
**Is your feature request related to a problem? Please describe.**
It's happened in multiple labs that `biasedChoiceWorld` is accidentally run for a mouse before it's considered trained. This then creates a weird situation for the data analysis, and is probably very demotivating for the animal (plus, we're no longer on our official training schedule).

**Describe the solution you'd like**
When selecting biasedChoiceWorld, check the training status of the mouse and give the user a warning (preferably a dialog box) that suggests they may have made an error.

**Comment by nbonacchi** [comment]
How would you check for training status?

**Comment by anne-urai** [comment]
The training status is on datajoint - or it could be recomputed in python
