### ISSUE TITLE
Test synching with devices upon launching pyBpod

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#222]
**Is your feature request related to a problem? Please describe.**
To avoid datasets with incomplete i/o data in the future, have a synch test (<10 seconds) that runs on the launching of pyBpod testing for:
- sound TTL
- FRAME2TTL
- Video frame TTL
(and other i/o if forgotten here) 

**Describe the solution you'd like**
Automatic test, short lasting, launched upon pyBpod start. 
No protocol selection involved, this is running before the GUI appears. 

It was requested by the Behaviour WG to have a prompt asking whether the protocol should be launched or not. 'No' launch would be used in the case of having an animal already in the setup and having to relaunch pyBpod (if crashed). 

**Describe alternatives you've considered**
Using test mouse and running a calibration protocol seems too comber some for the user to do it regularly enough. 

Messages once the mouse is already fixed are too late.

**Comment by anne-urai** [comment]
Suggested additions:
* check if water calibration was run within the last month
* check if proper frame2ttl calibration was run within the last month

**Comment by GaelleChapuis** [comment]
Suggested addition:
- do not allow to launch any training task if the test fails (so the user will not acquire bad data) ; can still launch calibration procedures.

**Comment by GaelleChapuis** [comment]
Suggestion: 
- calibration about to expire message (2 days prior to expiry date) -- make sure date isn't 1st Jan or so.
- if calibration is expired, ask user if they want to run without it (user should say no)

**Comment by GaelleChapuis** [comment]
What Anne has suggested is related to : https://github.com/int-brain-lab/iblrig/issues/312
