### ISSUE TITLE
When starting video recording, automatically select correct data folder

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#223]
**Is your feature request related to a problem? Please describe.**
When starting the `three_cameras_record.bonsai` workflow, all the video files are by default saved to the last used folder. This means that to save in the correct folder (that's just been created on the video pc), the user has to change the path in the Bonsai window 6x.

**Describe the solution you'd like**
It would be great if Bonsai could automatically find the folder that was created with `python .\prepare_video_session.py mouse_name`. Alternatively, the user could be prompted to select that folder manually, but ideally only once.

**Comment by nbonacchi** [comment]
Running three_cameras_record.bonsai manually will always mean taking care of where to save the data or the data will be saved in whatever default location the script has for testing (I believe it's the workflow folder itself). 
To automatically add the "correct" location please use the prepare_video_session.py script. It will open and start the stream file first so people can adjust cameras and run some checks and upon stopping and closing Bonsai it will automatically open the record file with all the filenames already inserted, it will NOT automatically start the recording as video should be the last thing to turn ON in a recording session.

**Comment by anne-urai** [comment]
Related request: if the user for some reason doesn't run prepare_video_script, the old video files are overwritten. Could there be a safety check where Bonsai throws an error if it's about to overwrite existing files?

**Comment by nbonacchi** [comment]
The proper usage is through the prepare_video_session.py script. User's entry point is through this script that ensures the files are saved in the appropriate location.
Running the bonsai workflow directly will save files in the workflow folder, overwriting them every time. This is the expected behavior for the workflow. 

If you run the workflow outside of the expected way of running it all bets are off...
