### ISSUE TITLE
increase default of videos to compress to 50

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#225]
**Is your feature request related to a problem? Please describe.**
We had an unnoticed backlog of videos that weren't compressed, currently compressing over the course of probably a week or so.

**Describe the solution you'd like**
To avoid this, it would be great to 1. give the user some sort of warning that the compression failed, and 2. increase the number of videos to be compressed each night to 50. For example: 3x behavior rigs, 6 mice/behavior rig/day = 18 videos. Then 1x ephys rig, 2 mice/ephys/day = 6 videos. Total: 20-30 videos (and that's without debugging or crashes that create small video files). 
In a high throughput lab, 20 seems on the low side. Could we up to to 50 to make sure no videos stay uncompressed?

**Comment by oliche** [comment]
Done.
