### ISSUE TITLE
Python script that automatically sets the camera settings

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#226]
**Is your feature request related to a problem? Please describe.**
When the PC is rebooted, it can happen that the camera setting file is set to default. It is cumbersome for the user to check manually each time that this has not happened.

**Describe the solution you'd like**
Write a script that automatically sets the camera settings to the correct settings before the behavioral task / recording starts.

**Comment by micheleangelofabbri** [comment]
Outdated request.
