### ISSUE TITLE
after pybpod update, settings for Display, user_settings, SoundCard will not change

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#232]
Now every time when there is pyBpod update we have to manually change settings in Bonsai workflow files to change name of the display(each stimulus) and Sound Card (remove 'xonar' when update is done in ephys rig). Additionally, in cortexlab I have to change in user_settings url address so sessions are connected to alyx.cortexlab.net instead of alyx.iternationalbrainlab.org

Can next updates be done without changing these files?

**Comment by nbonacchi** [comment]
RE 'xonar': Running the same code on two different hardware configs will always require user input. If the default was the other one one would have to change all other non ephys rigs for all tasks...
I can try to detect if you are on the ephys rig and change the value automatically by using the board name.
RE screens: I shared with you how I fixed it here in Lisbon. Try it out.
RE alyx: that is probably the only thing I cannot see how to change for you atm...

**Comment by anne-urai** [comment]
+1,  I was about to request something similar - for sessions like use_video, sync_square_x, sync_square_y, soft_sound, ambient_sensor it would be great to save them once per rig (just like the comports) so that they can be used across tasks, and stay consistent after updates.
