### ISSUE TITLE
Read contrast set of subject from Alyx at start of session -- Allow mice to swap across rigs

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/iblrig#234]
In trainingCW you have to train the animal in the same rig once new contrasts. Would be useful to be able to read in the contrast sets that were presented in the previous session so that there is flexibility in which rig you train the animal on

**Comment by GaelleChapuis** [comment]
@nbonacchi This is related to the fact of needing to be able to swap mice across triaining rig.

What we want:
1) if connection to Alyx is available, connect and get information (which means swapping across setups is possible).
2) if not, get data saved in local folder (in which case one would have to keep on training in the same rig)
