### ISSUE TITLE
after frame2TTL sync, settings file is not found

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#237]
**Describe the bug**
After running the `calibration_frame2TTL` protocol, the resulting settings file is not found - neither by the same protocol, nor by the training tasks. 
**Screenshots**
![img_20190808_140153 254](https://user-images.githubusercontent.com/6636245/62726515-61256200-b9e5-11e9-9d96-284958379db5.jpg)

**Additional context**
There are currently no instructions for how to run the frame2ttl calibration and syncing in the software setup document (https://docs.google.com/document/d/146UbxbsYDRUbXemlLY3HNdSxyEXgv--g4Tk7HuwZu9o/edit#heading=h.2m3x5rjh10v8) - should we copy the output values to a disk location where they can be retrieved easily?

**Comment by nbonacchi** [comment]
What do you mean?
From your screenshot I can see that whatever protocol you are running correctly connectes to Alyx, retrieved the thresholds you have just found and sent them to the device...
That info log is ablut SCREEN calibration files (which btw don't exist).

**Comment by anne-urai** [comment]
I see, I was under the impression that `PREVIOUS_DATA_FILE` would be the previous file from the same calibration. Thanks!
