### ISSUE TITLE
Hardware connection metadata file

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#238]
**Is your feature request related to a problem? Please describe.**
When doing analysis, we need to know which hardware (e.g. frame2ttl) corresponds to which channel on the spikeglx_synch.channels npy file (e.g. 12).

**Describe the solution you'd like**
A metadata file for the hardware connection, listing the port number as seen on the hardware, and the corresponding hardware apparatus connected to it.

This file has to be maintained by the user, and associated on a session-by-session basis (in case the setting changes - one can well imagine this happening in the case of a port breaking or if more i/os are needed). 

For example, a `hardware_settings.json` containing
```
SYSTEM:{"3A"}, 
DIGITAL IO PORT ": {
  "P0.0": "Imec synch signal",
  "P0.1": "Audio input",
[...]
 },
ANALOG IO PORT :  etc
```

Another function can then be launched to do the mapping between hardware port and spikeglx output (e.g. port P0.0 corresponds to channel 1 -- making these numbers up as example).

Document where the port-hardware correspondence is defined (can be the default setting):
https://docs.google.com/document/d/1__SyIdvndvojfS4qg027c-h3QpMDH9oz8J3PAbGR-f8/edit

**Describe alternatives you've considered**
Hardcoding values in analysis scripts.

**Comment by oliche** [comment]
Current template for 3A probes:

```

**Comment by oliche** [comment]
over to you @nbonacchi, we need the rig to somehow spit out a `neuropixel_wirings.json` for 3A with the format above. Will update when 3B is ready.

**Comment by nbonacchi** [comment]
@oliche Do you have any preference of the location?
can be in `raw_ephys_data/neuropixel_wirings.json` or as a variable called NEUROPIXEL_WIRING in the `raw_behavior_data/_iblrig_taskSettings.raw.json` file

I'd suggest using an ALF compatible name like **_iblrig_neuropixel.sync_channelsID.json**

**Comment by oliche** [comment]
@nbonacchi there will be one file per probe as it's different for each. I'm thinking about

```

mock_certification_g0_t0.imec1.ap.bin
mock_certification_g0_t0.imec1.ap.meta
mock_certification_g0_t0.imec1.lf.bin
mock_certification_g0_t0.imec1.lf.meta
mock_certification_g0_t0.imec1.wirings.json
```

**Comment by oliche** [comment]
3B nidq file
```
{'SYSTEM': "3B",
 'SYNC_WIRING':
     {
         "P0.0": "left_camera",
         "P0.1": "right_camera",
         "P0.2": "body_camera",
         "P0.3": "sync",
         "P0.4": "frame2ttl",
         "P0.5": "rotary_encoder_0",
         "P0.6": "rotarty_encoder_1",
         "P0.7": "audio",
     }
 }
```

**Comment by GaelleChapuis** [comment]
For 3A:
"pin05": "Camera level shifter board ground",  
> rewrite to 
"pin05": "camera_level_shifter_board ground" for consistency

  "pin20": "audio",
> rewrite to
  "pin20": "audio ground",

https://github.com/int-brain-lab/ibllib/blob/sync_ephys_qc_bpod/tests/ibllib/extractors/test_ephys_fpga.py
> 404 page not found

**Comment by GaelleChapuis** [comment]
I would put the info on the hardware wiring in the taskSetting file (is that a local file that then gets copied and transferred in the session?), not in the probe file - as there is only 1 HW wiring per experiment.

**Comment by GaelleChapuis** [comment]
For 3B:

SYNC_WIRING
> rename to
SYNC_WIRING_DIGITAL

Rename some variables and include analog signal:

{'SYSTEM': "3B",
 'SYNC_WIRING_DIGITAL':
     {
         "P0.0": "left_camera",
         "P0.1": "right_camera",
         "P0.2": "body_camera",
         "P0.3": "Imec_sync_signal",
         "P0.4": "frame2ttl",
         "P0.5": "rotary_encoder_0",
         "P0.6": "rotarty_encoder_1",
         "P0.7": "audio",
     }
 'SYNC_WIRING_ANALOG':
     {
       "AI0": "bpod",
     }
 }

**Comment by oliche** [comment]
3B json:
```
{
    "SYSTEM": "3B",
    "SYNC_WIRING_DIGITAL": {
        "P0.0": "left_camera",
        "P0.1": "right_camera",
        "P0.2": "body_camera",
        "P0.3": "imec_sync",
        "P0.4": "frame2ttl",
        "P0.5": "rotary_encoder_0",
        "P0.6": "rotary_encoder_1",
        "P0.7": "audio"
    },
    "SYNC_WIRING_ANALOG": {
        "AI0": "bpod"
    }
}
```

3A json
```
{
    "SYSTEM": "3A",
    "SYNC_WIRING_DIGITAL": {
        "pin03": "left_camera",
        "pin04": "right_camera",
        "pin05": "camera_level_shifter_board_ground",
        "pin06": "body_camera",
        "pin09": "bpod",
        "pin10": "bpod_ground",
        "pin15": "frame2ttl_ground",
        "pin16": "frame2ttl",
        "pin17": "rotary_encoder_0",
        "pin18": "rotary_encoder_1",
        "pin19": "audio",
        "pin20": "audio_ground",
        "pin23": "rotary_encoder_ground"
    }
}
```
