### ISSUE TITLE
spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#244]
I was not able to successfully install spinnaker_python in video computer:
```
(iblenv) C:\Users\IBL-Video-Experiment>pip install ~\Downloads\spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl
Requirement '~\\Downloads\\spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist
spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```
python 3.6 already exists in (...)\envs\iblenv

I followed these steps described in guide for software installation for ephys video computer: 

conda create -y -n iblenv python=3.6
conda activate iblenv
pip install ibllib
pip install ~\Downloads\spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl
conda install -y git
cd c:\
git clone http://github.com/int-brain-lab/iblscripts.git

**Comment by nbonacchi** [comment]
The error message says:
Requirement '~\\Downloads\\spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist

are you sure the path is correct to the file?

**Comment by karolinasocha** [comment]
yes:

```
(iblenv) C:\Users\IBL-Video-Experiment\Downloads>pip install spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl
ERROR: spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by karolinasocha** [comment]
I installed everything again and had the same error during installation.
I used command `pip install pyspinnaker` to see if that will fix the issue with installation but it did not: 

```
(iblenv) C:\iblscripts\deploy\videopc>python .\prepare_video_session.py mouse_name
Traceback (most recent call last):
  File "C:\iblscripts\deploy\videopc\config_cameras.py", line 8, in <module>
    import PySpin
ModuleNotFoundError: No module named 'PySpin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\prepare_video_session.py", line 12, in <module>
    import config_cameras as cams
  File "C:\iblscripts\deploy\videopc\config_cameras.py", line 14, in <module>
    "Installing_the_video_acquisition_computer")
ImportError: ('PYSPIN MODULE NOT FOUN IN ENV', 'Please follow the wiki instructions here:', 'https://wiki.internationalbrainlab.org/index.php/Installing_the_video_acquisition_computer')

(iblenv) C:\iblscripts\deploy\videopc>ll last):
'll' is not recognized as an internal or external command,
operable program or batch file.
```
I checked version of python and it is 3.6 as it was also before:

```
(iblenv) C:\iblscripts\deploy\videopc>python --version
Python 3.6.9 :: Anaconda, Inc.
```

**Comment by karolinasocha** [comment]
ok, the issue was related to the location of that file. Following instructions I kept spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl file in "Download" folder. I moved that file to C:\iblscripts\deploy\videopc and then successfully installed the file. 

`pip install C:\iblscripts\deploy\videopc\spinnaker_python-1.20.0.15-cp36-cp36m-win_amd64.whl`
