### ISSUE TITLE
do not display camera sync warning message when record_video=False

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#249]
**Is your feature request related to a problem? Please describe.**
When doing behavioral on the ephys rig (which doesn't have a camera plugged in), pybpod still gives warnings that there is no camera sync signal detected.

**Describe the solution you'd like**
It would be great if the camera sync warning was disabled when `record_video=False`.

**Comment by GaelleChapuis** [comment]
The camera 1 (60Hz) is plugged into Bpod during behavior. Bpod should thus give a warning if it is indeed not detecting a synch signal.
