### ISSUE TITLE
Frame2ttl unreliable data when wheel moves

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#252]
**Describe the bug**
Accordingly to Nicco, the frame2ttl does not output the expected trace when the wheel moved. 

We need to test for the reliability of the frame2ttl separately from the task software. 

**To Reproduce**
Record in rig. 

**Expected behavior**
The frame2ttl should perfectly follow the synch square signal. 

**urgent need**
To test this, have a Bonsai workflow that switches the synch square (or even the whole screen if less complex) at the screen refresh rate (60Hz), for a set number of times (1000 for example).

If the Frame2ttl data has the expected number of switches, we can state with confidence the hardware is not faulty.

**Comment by nbonacchi** [comment]
I ran a sw sanity check to see when I send the commands to update the screen...
I asked it to flip every frame at 120, 100, and 60Hz

[times120Hz.txt](https://github.com/int-brain-lab/iblrig/files/3545865/times120Hz.txt)
[times60Hz.txt](https://github.com/int-brain-lab/iblrig/files/3545866/times60Hz.txt)
[times100Hz.txt](https://github.com/int-brain-lab/iblrig/files/3545867/times100Hz.txt)

This is the output of Bonsai that I send to the GPU and the timestamp of when send it. 
You can ignore the first columns and only look at the last. I haven't loaded it and computed the diff yet but visually inspecting the files they seem to be OK. 
Meaning, 120Hz ~8ms diff; 100 Hz ~10ms diff: and 60 Hz ~ 17ms diff. This means that We're able to drive the GPU at the correct rate. FRAPS confirms the GPU responds appropriately, so I doubt the GPU's the problem.
The limitation seems to be either in the screen refresh rate and some weird harmonic when the switches happen too fast that skips a frame or the frame2TTL detection, to be sure I'd need a 120Hz screen that I can run the test on and see the frame2TTL output follow that frequency. If that's the case it's the screen.

**Comment by GaelleChapuis** [comment]
@nbonacchi we can record the 60Hz with a camera.

Could you send us the Bonsai workflow that 1. switches the signal at 60Hz 2. has a bigger synch patch so we can acquire it via camera and frame2ttl

**Comment by GaelleChapuis** [comment]
Ok - now that we did some tests, it seems that:
1. the screen is reliable
2. the frame2ttl is reliable

The issue is in the Bonsai workflow, when there are several screen changes in a row that are below the refresh rate limit of the screen

Screen Frame 1.    -   2.   -   3. 
Wheel move  1.  2.   3. 4.5. 6.
Binary :           1.  0.   1. 0.1. 0.   1: White, 0: Black

In the example case above, we'll see only a change in frame2TTL signal at frame time 1.  and 3. - whilst in the middle the stimulus position changed.

The workflow needs to be amended so that:

1. all commands sent to the screen via Bonsai are saved in metadata (timestamps, and stimulus properties (position notably) command)) - marking the time when the screen is actually update (can be a binary vector)
2. when the screen is updated (and only then), change the synch square colour
