### ISSUE TITLE
sync square not correctly placed in new bpod_ttl_test

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#254]
**Describe the bug**
With the current settings, the sync square appears in the top center of the screen. With `SYNC_SQUARE_X=1.33` and `SYNC_SQUARE_Y=-1.03`, the square appears on the bottom right where the frame2ttl sensor is.

**Comment by GaelleChapuis** [comment]
Would these parameters be good if applied to all pyBpod tasks ?

**Comment by anne-urai** [comment]
yes, I suggest these defaults: https://github.com/int-brain-lab/iblrig/issues/184
