### ISSUE TITLE
Pre-assignment of session to one of multiple subject projects

### ISSUE THREAD

**Issue by ineslaranjeira** [int-brain-lab/iblrig#259]
Some subjects might be assigned to more than one project, but sessions are necessarily assigned to one single project. At the moment, there is no explicit way for the user to define the project of a session, which potentiates misattribution of session projects.
It would be useful if in the beginning of each session the user is asked to select the appropriate project for that session.

**Comment by GaelleChapuis** [comment]
This is related to: https://github.com/cortex-lab/alyx/issues/606
