### ISSUE TITLE
ephysChoiceWorld does not run when you select Bregma in GUI v.6.0.0

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#263]
**Describe the bug**
When you select Bregma or Lambda in GUI ephysChoiceWorld, the task does not start and gives this error:
```

System.InvalidOperationException: Sequence contains no elements.
Connected to https://alyx.cortexlab.net as Karolina_Socha
done

```

However, if you do not select this field (with Bregma and Lambda) and just enter values for X,Y,Z, D, and angles then the task starts normally.

**Comment by nbonacchi** [comment]
Maybe this bug is related to #265 ?
I just retested here and it seems to work, @anne-urai  also has not complained about this when recording, did you play around with the drop down menu, can you reproduce the issue @anne-urai ?

**Comment by anne-urai** [comment]
I didn't have this problem yesterday but I also did not touch the dropdown menu - the default was Bregma so I left it like that. Can try today what happens if I select it actively.

**Comment by karolinasocha** [comment]
If you do not select then pybpod not crash - as it was in previous version; when you click on the field and you chose Bregma or Lambda then the task does not start.
