### ISSUE TITLE
Bonsai video recording crashes with a memory error (on ephys video PC)

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#264]
**Describe the bug**
When running `python prepare_video_session.py` on the ephys video PC, folders are created, the camera stream opens and when I close that, recording starts. After a while though, the recording stops with a memory error. The disk to which I'm saving the video files has plenty of memory.

**Screenshots**
![evernote53315568372407295471389919740](https://user-images.githubusercontent.com/6636245/65994758-19a9d800-e462-11e9-8c8c-a71d4abfa069.jpg)

**Comment by nbonacchi** [comment]
The error is about RAM memory not HD/SSD memory. It looks like the RAM is not able to process all the frames is receiving which makes the buffer of frames to be saved to increase over time, are your frame rates configured properly?

**Comment by anne-urai** [comment]
Related to https://github.com/int-brain-lab/iblrig/issues/226
