### ISSUE TITLE
pybpod hangs, requires user to press 'enter' in conda prompt to continue

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#267]
**Describe the bug**
When running either `trainingChoiceWorld` or `biasedChoiceWorld`, the experiment sometimes hangs between trials - nothing is shown on the screen and the mouse sits waiting. The experiment only continues when 'enter' is pressed in the conda prompt to get Python going again. 

**Screenshots**
This video shows what happens https://photos.app.goo.gl/HuEqaGqNnWXwjTV69.

**Additional context**
I'm not yet sure if these accidentally long ITIs are correctly logged in the data.

**Comment by nbonacchi** [comment]
This is a known problem with windows, here's the response to the same issue #181 I shared with karolina...
You'll loose the ability of copy pasting from the terminal but it seems to help with the problem.

https://github.com/int-brain-lab/iblrig/issues/181#issuecomment-481246715
