### ISSUE TITLE
starting the biasedCW will not depend on detecting camera pulses

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#272]
I would like to remove the condition from the biasedCW protocol that it starts only when the camera pulse is detected.

**Comment by GaelleChapuis** [comment]
Related : write in doc https://docs.google.com/document/d/1jwqQJWfTEwZgLKsjBVf0TRSu6QiXVvspladlxDh-CIs/edit documentation on how to use Bonsai / video computer in ephys rig (so as not to have to unplug the camera from the computer and do the extraction)
