### ISSUE TITLE
ipad screens way too bright following gamma correction

### ISSUE THREAD

**Issue by njmiska** [int-brain-lab/iblrig#273]
We (everyone) recently applied a gamma correction to ipad screens in order to remove the stimulus artifact that has been appearing at zero contrast.  However, as a result of this gamma correction, all ipad screens now are roughly *double* the previous brightness values.  Is there a way we could bring the brightness back down without reinstalling new polarizing filters?  Alternatively, is there a way to remove the zero contrast stimulus artifact while keeping the default gamma correction values?

**Comment by anne-urai** [comment]
After restarting the PC, make sure to go to the NVIDIA panel again, and redo the 2.35 gamma setting (and click 'Apply' again). Then the luminance should go back to normal (can confirm with luminance meter)

**Comment by GaelleChapuis** [comment]
@njmiska Could you please confirm the solution Anne worked, so we can close the issue?

**Comment by njmiska** [comment]
No, did not work. Anne, can you please clarify, is this a method you used to adjust gamma to 2.35 and bring the ipad screen brightness back down to ~50 without installing new polarizing filters?  I had thought we just decided to install new filters.  If that is the case, then I will close this.

**Comment by anne-urai** [comment]
@njmiska if you have done the correct gamma settings once, put the right filters and confirmed the luminance, then the trick is to re-do the gamma settings after restarting the PC. So yes you'll have to redo the film once, and then re-apply the settings after each PC reboot.
