### ISSUE TITLE
Make BiasedCW aware of rig type, (do not open camera)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#274]
**Is your feature request related to a problem? Please describe.**
Currently, in order to *train* mice on the *ephys* rig, one has to unplug one of the cameras from the video PC and plug it into the behaviour PC - Then adjusting the COM port, frame rate etc. 
This is precarious, and can lead to errors. Moreover, it sometimes fails and the Bpod task is left hanging, rendering animal training impossible. 

**Describe the solution you'd like**
Never have to touch the hardware connections on the ephys rig. 
To achieve this, make a new behaviour task (called `biasChoiceWorld_ephysRig`) that will :
1) be the same code as ephysChoiceWorld, with the exception that 30 randomly generated sequences are used 
2) wait for video trigger from 1 camera only 
3) the Bonsai script launching the videos has to be adapted (should the camera frame rate be set to 30Hz? Can Bpod handle higher rates? Issue on the registration/space if frame rate > 30Hz?)

**Comment by nbonacchi** [comment]
Should make a prepare_session_biased.py on videopc that sets the framerate and opens only one camera. To be done when coding the interface with other cameras for ephys...
