### ISSUE TITLE
In coordinate window (ephysChoiceWorld), add signs to facilitate quick user entry

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#278]
**Is your feature request related to a problem? Please describe.**
When entering the coordinates for probe insertion, the user has to consult the guide to know which direction corresponds to -/+. 

**Describe the solution you'd like**
Add signs to the GUI itself, e.g. -A +P, -D +V, etc.

**Describe alternatives you've considered**
Another option (probably a lot more work) is to show the picture from the guide in the GUI.

**Additional context**
Related: https://github.com/int-brain-lab/iblrig/issues/218 it would be great to be able to enter or these coordinates after the session, as entering them takes quite a bit of time.

**Comment by anne-urai** [comment]
See here https://docs.google.com/document/d/1ZKWt7yKx6r-6acZ2Lm4ZSMKL_IVwTGJH1Fg180SSA-k/edit for shortcuts

**Comment by GaelleChapuis** [comment]
You can hover over the labels for description. This has been added to the guide.
![image](https://user-images.githubusercontent.com/43007596/70141919-58455400-1698-11ea-91f6-3f7dfdae5f69.png)
