### ISSUE TITLE
Hardware metadata (luminance)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#279]
**Is your feature request related to a problem? Please describe.**
The user need to be able to login values regarding changes in the hardware onto Alyx.
Current values that need input:
- Luminance of the screen (mesured using Lux meter)

**Describe the solution you'd like**
A corresponding JSON field in a parameter file.

**Comment by nbonacchi** [comment]
Lab locations jso currently looks like this:
{
  "NAME": "_iblrig_angelaki_ephys_0", 
  "COM_BPOD": "COM12", 
  "COM_ROTARY_ENCODER": "COM5", 
  "COM_F2TTL": "COM2", 
  "F2TTL_DARK_THRESH": 86.0, 
  "F2TTL_LIGHT_THRESH": 46.0, 
  "F2TTL_CALIBRATION_DATE": "2019-11-06", 
  "WATER_CALIBRATION_RANGE": [50.0, 200.0], 
  "WATER_CALIBRATION_OPEN_TIMES": [50.0, 100.0, 150.0, 200.0], 
  "WATER_CALIBRATION_WEIGHT_PERDROP": [3.099, 9.367, 16.3, 23.299], 
  "WATER_CALIBRATION_DATE": "2019-11-11"
}

I could add a script for people to measure the lux that updates this with:
  "SCREEN_LUX_VALUE": ####,
  "SCREEN_LUX_DATE": "yyy-mm-dd"

**Comment by GaelleChapuis** [comment]
Related to https://github.com/int-brain-lab/iblrig/issues/312

**Comment by nbonacchi** [comment]
On develop
