### ISSUE TITLE
enter delay in ephysChoiceWorld

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#280]
**Is your feature request related to a problem? Please describe.**
Just like in biasedChoiceWorld, have a delay pop-up box in ephysChoiceWorld. This way, the task can be launched immediately upon closing the door and starting recording, allowing the probes to settle in the brain for a bit.

**Comment by nbonacchi** [comment]
I asked this on slack already:
Isn't the delay of biased there to mimic the delay that animals have to go through in a recording session? I don't understand the relevance of this delay?

**Comment by anne-urai** [comment]
The brain needs to settle around the probes in order to let the tissue stabilize

**Comment by GaelleChapuis** [comment]
Is this now implemented ? And if yes, what is the GUI like ?

**Comment by GaelleChapuis** [comment]
This was closed because it will mess up the task logic and is too complex to implement. We will instead ask the user to time probe settling using a manual timer.
