### ISSUE TITLE
Mock ephysChoiceWorld - How to deal with data extraction

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#282]
**Is your feature request related to a problem? Please describe.**
Once an animal is placed on the ephys rig and has passed the criterion 'ready4delay', experimentalists have to do at least one session mimicking the protocol used during recording, i.e. mock "ephysChoiceWorld" , for the animal to be considered 'ready4recording'.

In terms of the data, this mock "ephysChoiceWorld" will only contain behavioral data of interest as in "biasedChoiceWorld".
How to distinguish a mock "ephysChoiceWorld" VS a real "ephysChoiceWorld" session is the debate here.

Note: the camera data could be saved to train the DLC network.

**Describe the solution you'd like**
A new protocol "mock_ephysChoiceWorld" that calls the same code as "ephysChoiceWorld" (i.e. no duplicate of code, just a different alias).
Olivier recommends naming the protocol xxx_biasedChoiceWorld  (where xxx = mockEphys ?)

**Describe alternatives you've considered**
A "mock: yes/no" toggle button that appears on the GUI when selecting "ephysChoiceWorld". This could be dangerous if left at "yes" by error (could make the default "no"?).

**Comment by GaelleChapuis** [comment]
We should use this recording type to test the connectivity between Bpod / apparatus and FPGA/PXI.
So the extraction of the FPGA/PXI TTL pulses and cameras should be done as is in the ephysChoiceWorld protocol.

**Comment by nbonacchi** [comment]
If it's a mock ephysCW recording it should be ephys code and extraction, if you are worried about the session sequence I can easily generate a couple of mock recording sessions that would be loaded if users select "mock recording" from an option on the GUI.

**Comment by GaelleChapuis** [comment]
I am worried about the fact that if we keep the same task protocol name, when looking for session to analyse we will hit those too.

The easiest would be to have a protocol called "mockEphysCW" that underneath calls "ephysCW".
The extraction though is done as is for "biasedCW" on the ephys rig, with the exception of the TTL_test.py (@oliche maybe this needs "ephysCW" extraction though?)

**Comment by nbonacchi** [comment]
Why would we do that? 
It's a full run of ephys with recordings et al. we have the extractor for this protocol.
The only difference from a "real" ephysTask is that the experimenter does not put the probes inside the brain, so it is exactly like running e.g. biasedCW with a different set of  contrasts. The ephys recording should have all the sync pulses but have no spikes (which is probably a good negative control to have for KS2) so we might even go ahead and decide to try and spike sort the saline. To query for ephys sessions in terms of behavior we should be able to use the data, and in terms of spikes this session will be automatically "ignored" in two ways, first KS2 output should show yow no spikes so nothing to align to any event; second the ephys QC should not pass.
