### ISSUE TITLE
Procude warning when cameras started prior to task in ephys rig under ephysChoiceWorld 

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#283]
**Describe the bug**
Currently, camera input are required for the task ephysChoiceWorld to start.
This creates a synching discrepancy if the camera are turned ON before the task. 

**To Reproduce**
Start the cameras, start the task. Number of TTL pulses will be different across apparatus. 

**Expected behavior**
SW checks if cameras input TTLs are receive shortly (<3/Fs, where Fs is the sampling freq of the slowest device). If it does, output a warning message (or even error?) asking for the device to be turned off and the task restarted

**Comment by nbonacchi** [comment]
There's no way to ask the ephysPC if it detects pulses in the camera syncs of the FPGA. There's no way to ask the videoPC if the video is running. Similarly there's no way to ask the behaviorPC without running the task if one of the cameras is sending pulses...

I'll close this for now, to be reopened if we end up implementing the whole small pre-task run before actual run...
