### ISSUE TITLE
slow transfer speed to server PC using iblscripts

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#287]
When manually transferring (drag-and-drop in Windows File Explorer) about ~1hr of ephys recording for 2 probes, copying takes around 30 minutes. When doing the same thing using the `transfer_ephys_data` script, the same operation takes several hours.

A similar slowdown is observed for video transfer.

**Comment by GaelleChapuis** [comment]
For https://github.com/int-brain-lab/iblscripts/issues
