### ISSUE TITLE
don't wait for camera pulses if record_camera and show_camera are false

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#291]
**Describe the bug**
If a behavior rig camera does not work (for whatever reason), training protocols won't launch.

**Expected behavior**
If the user sets `RECORD_VIDEO = False` and `OPEN_CAMERA_VIEW = False`, the task should *not* wait for camera pulses before starting.

**Comment by nbonacchi** [comment]
We don't want to acquire incomplete sessions, if really needed for some reason, you can not record video but OPEN_CAMERA_VIEW should be ON this will trigger the behavior.

**Comment by anne-urai** [comment]
now, if OPEN_CAMERA_VIEW = True but the camera is broken (i.e. not sending pulses) then the task does not start. can that be changed?

**Comment by nbonacchi** [comment]
The question is do we want to allow acquisition of data with no camera. There are 2 main forces at play here, on one hand people want something flexible to try stuff out, on the other we want that data that goes through the pipeline is data we can actually use. If the camera is broken, I guess the camera should be fixed before using the rig again, and if it brakes you would want to know this ASAP.
If not all devices are present though I guess you should be able to run the tasks even if the data will not be used and passed through the pipeline.
I can bring this up in the next data meeting, but might be a decision for the analysis groups, i.e. how much of the session has to be present to use this session on analyses? Basically what are the criteria for a session to be considered OK for analysis and consequently OK for upload.

**Comment by anne-urai** [comment]
yes this is a good question - I'd say if the camera is broken and animals are in a critical early stage of learning, it's worse to pause training (potentially messing up their learning curves and substantially prolonging the experiment) than to have a few sessions without video. Who should decide this you think?

**Comment by GaelleChapuis** [comment]
The Analysis WGs would like to have video (generally speaking, complete) data, obviously. I suggest we focus on enabling mice to be trained in different rigs (in case of a camera breaking on one of the training rigs) ; if a camera is not working on the ephys rig, no experiment should be run on it anyway until it is fixed.

**Comment by GaelleChapuis** [comment]
Focus on : https://github.com/int-brain-lab/iblrig/issues/234
