### ISSUE TITLE
cannot transfer video data if raw_video_data folder already exists

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#296]
**Describe the bug**
After running the transfer to server of *behavioral* data from the ephys behavior rig, the server PC will have the `raw_behavior_data` folder, but also a `raw_video_data` file that only contains `_iblrig_videoCodeFiles.raw`.

When then running `transfer_video_session.py`, the transfer cannot complete because the `raw_video_data` folder already exists:
```FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\iblserver.cshl.edu\\ibldata\\Subjects\\CSHL_012\\2019-11-22\\001\\raw_video_data'```

**Proposed solution**
Can the transfer script skip the creation of folders when they already exist, and put the video and timestamp files into the existing folder?

**Comment by nbonacchi** [comment]
This is like this by design... there should not be a video folder in the server, at this moment unless one creates it manually it shouldn't be there.

**Comment by anne-urai** [comment]
Let me re-state the problem: when running `biasedChoiceWorld` on the ephys rig (for training), a folder `raw_video_data` is created (containing only `iblrig_videoCodeFiles.raw`). Can the creation of this file, and the folder, be avoided?

**Comment by nbonacchi** [comment]
Lines 43 to 48 in session params of biased task should now prevent creation of video folder if on ephys rig, although now that I think about it I don't think I stopped the file creation, maybe it still creates the folders? Let me know if this will applies after lastest update by reopening then

**Comment by anne-urai** [comment]
Today we ran two animals in `_iblrig_tasks_biasedChoiceWorld6.2.0` on the ephys rig, and this file is still created
