### ISSUE TITLE
block probability incorrectly coded/extracted in ephysChoiceWorld

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#297]
**Describe the bug**
Nick discovered that e.g. in CSHL_015/2019-11-11/001, the probabilityLeft in ONE has the first 90 trials as 50/50, then presumably correctly indicates the next block is 20/80, but then for some reason reports that alternating trials are 80/20 and 20/80
![image](https://user-images.githubusercontent.com/6636245/69733698-c370b280-10fb-11ea-9e97-7ab78cbf9419.png). A few other `ephysChoiceWorld` subjects (e.g. SWC_005, 2019-11-21 17:11:10) have the same issue.

**Comment by karolinasocha** [comment]
Any update on that issue? It seems that this has an effect on psychometric curves generated in DJ and hence on indication if the animal is ready for ephys recordings. 

![image](https://user-images.githubusercontent.com/32096962/71837245-d8067a00-30ad-11ea-968a-603f8e7bbbce.png)

In this case, the animal did not show the shift during the task but I am not sure if that is true behavior or result of faulty extraction.

**Comment by karolinasocha** [comment]
is there a way to get correct information about the bias block probability (before extraction)? I tried to find in the behavior task file: __iblrig_taskData.raw_; However, I did find information about correct probability. I thought that number in _block_len_ relates to the fixed probability but I checked different sessions and this probability can also change.

**Comment by anne-urai** [comment]
overview of the extent of this issue: https://github.com/int-brain-lab/analysis/blob/master/python/ephysCW_probLeft_check.ipynb looks like it's mostly fixed in ONE, but not all propagated to DJ
