### ISSUE TITLE
prepare_video_session --training does not open video streams when recording

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#299]
**To Reproduce**
When running `prepare_video_session --training` on the video PC (when training animals in biasedChoiceWorld on the ephys rig), the 3 windows open for the first streaming Bonsai workflow. When the streaming workflow is closed, the recording workflow opens as it should. When clicking 'start' on this second workflow, the recording starts (files are saved) but no windows pop up on the screen. This means that the animal can't be monitored during training.

**Comment by GaelleChapuis** [comment]
@nbonacchi what did you do to close the issue? Please write in the issue itself so we know, thanks :) !

**Comment by ineslaranjeira** [comment]
This issue can be solved by double clicking on the Image node on the Bonsai workflow.

**Comment by anne-urai** [comment]
Thanks so much @ineslaranjeira ! For the record: after launching `three_camera_record_biasedCW.bonsai` and starting the workflow, the camera window won't show. While the workflow runs, double clicking on the `Image` node will open the camera view.
