### ISSUE TITLE
define list of sessions for automated copying to local server

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#302]
Automated copying data overnight, without input from the experimenter/user.

Description: 
Copying ephys data takes around 2.5 hours (2 probes, 1 hour of recordings) to the local server; It always asks if you want to copy to a specific folder and the user has to confirm this by typing 'yes' and execute it. If there are more than 2 or 3 sessions to copy then after 3 hours the experimenter has to repeat this. If it does not then the data is not copied and it waits for confirmation from the user.

Request:
If you run more than 2 recordings sessions it will be a good improvement to just define the session names to copy and leave this overnight (automatically, without input from the user). Otherwise, after copying each session it requires the experimenter to confirm copying the next session.

**Comment by nbonacchi** [comment]
Yes, definitely. We were talking about this with @anne-urai and it's in my backlog

**Comment by anne-urai** [comment]
Moved to https://github.com/int-brain-lab/iblscripts/issues/25
