### ISSUE TITLE
Compare Bonsai and Frame2TTL output

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#304]
**Is your feature request related to a problem? Please describe.**
We need to do this test so as to know if the issues we see if coming from HW or SW.
Compare the number of screen change command sent via Bonsai, to the number of frame2ttl state change (do overall and per trial).

**Comment by chiyu1203** [comment]
@GaelleChapuis Hello! This might be off-topic but I am a PhD student studying dessert locusts in Germany. I have been trying to establish a method to relay the analog signal (light level) of frame2TTL v3 to Bonsai, but did not make much progress in the past one year. Do you know if there is any way to do so?
Best Regards
Chiyu
