### ISSUE TITLE
 Rig computer freezes after entering poop count

### ISSUE THREAD

**Issue by khanalanup** [int-brain-lab/iblrig#306]
**Description of the bug**
The rig computer froze after entering poop count for one of the mice (CSHL055). I had to restart the computer. 
I did not have issue running other mice on the same rig, however came across this error when I tried running CSHL055. 

**Screenshot is attached.**
![IMG_20191220_113109](https://user-images.githubusercontent.com/59095503/71271001-f126d100-2320-11ea-8c44-99f023291048.jpg)

**Comment by GaelleChapuis** [comment]
@khanalanup is this a bug that is still recurrent? Or can we close the issue?
