### ISSUE TITLE
no stimulus in ephysChoiceWorld and passiveChoiceWorld v.6.3.1

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#308]
In ephys rig (Neuropixels 3B), pybpod version 6.3.1, I have an issue with recording protocols:
1. ephysChoiceWorld - there is no stimulus generated and displayed. However, the session starts giving the sound cue to start the trial. There was no error message in the command window.
2. passiveChoiceWorld protocol did not run (I click "run" but did not do anything) and there was no error message at all.

**Comment by GaelleChapuis** [comment]
@karolinasocha in 1., by no stimulus, do you mean no **visual** stimulus ?

**Comment by GaelleChapuis** [comment]
Similar issues in 2 other lab (Fei + Anne) : https://int-brain-lab.slack.com/archives/CEM70EXTN/p1577996565014100

**Comment by njmiska** [comment]
+1, we are also having this exact same problem.  no stimulus displayed in ephysCW in v.6.3.1

**Comment by guidomeijer** [comment]
+1, reproduced the bug on my rig
