### ISSUE TITLE
no sounds play in bpod_ttl_test on ephys rig

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#309]
All sound pulses are missed, and no beeps are played. The `bpod_ttl_test` runs fine on behavior rigs. Other tasks in the ephys rig play normal sounds.

**Comment by GaelleChapuis** [comment]
Cortex lab has the same issue

**Comment by GaelleChapuis** [comment]
This is only in v.6.3.1, no 6.2.5, correct ?
