### ISSUE TITLE
record_mic Bonsai workflow fails to launch on ephys rig

### ISSUE THREAD

**Issue by ineslaranjeira** [int-brain-lab/iblrig#310]
The record_mic Bonsai workflow fails to launch properly when running biasedChoiceWorld on the ephys rig (pybpod version 6.3.1).

![record_mic](https://user-images.githubusercontent.com/38464551/71829257-21e66480-309c-11ea-9205-1f8c88822e59.png)

**Comment by anne-urai** [comment]
same at CSHL
