### ISSUE TITLE
passiveCW freezes at some point during trial replay

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#311]
https://int-brain-lab.slack.com/archives/CEM70EXTN/p1576018274246800

**Comment by nbonacchi** [comment]
This is 6.2.5?

**Comment by anne-urai** [comment]
Yes 6.2.5

**Comment by karolinasocha** [comment]
I have the same issue, it seems that freezes after RF mapping (sparse noise)

**Comment by anne-urai** [comment]
i found out today that when passiveCW hangs, clicking Stop Trial in pybpod will make it continue. not sure if sync pulses are then still correct.
