### ISSUE TITLE
monthly check for calibration

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#312]
**Is your feature request related to a problem? Please describe.**
Finding a way to make sure calibration are run regularly.

**Describe the solution you'd like**
Have a way to save the calibration files/date when made. After a month has passed since the last calibration, send the user a reminder (e.g. python terminal upon launch of pyBpod, or better as prompt in GUI) to do the following checklist:

- water calibration, check tubing
- screen luminance measurement, gamma calibration + frame2ttl test
- camera positioning, focus and exposure
- temperature and fan functioning
- distance mouse - screen

**Describe alternatives you've considered**
On the 1st Monday of each month, send the user a reminder (email) to go through the following checklist:
https://github.com/cortex-lab/alyx/issues/558
 It was decided it should not be done via Alyx+email

**Comment by GaelleChapuis** [comment]
For the screen luminance, there is currently no specific field for it. Could it be added in the JSON file or so, so it's easily retrievable for analysis? We could save 5 values, at the screen center plus corners.

**Comment by nbonacchi** [comment]
Enforced delays between calibrations>
```python
thresh = {
        "F2TTL_CALIBRATION_DATE": datetime.timedelta(days=7),
        "SCREEN_FREQ_TEST_DATE": relativedelta(months=4),
        "SCREEN_LUX_DATE": relativedelta(months=4),
        "WATER_CALIBRATION_DATE": relativedelta(months=1),
        "BPOD_TTL_TEST_DATE": relativedelta(months=4),
    }
```

**Comment by micheleangelofabbri** [comment]
Outdated request.
