### ISSUE TITLE
adding information about the hemisphere and intended location of recordings in pybpodGUI

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#315]
In pybpod GUI, in ephysCW, we just type information about the coordinates from the manipulator.
I would like to suggest adding 2 additional fields (and save it in JSON file):
1. An additional field that indicates which hemisphere was recorded. Now this is information is extracted from the manipulator position for "x" value (lateral-medial); if positive - right hemisphere; if negative - left? Adding **Hemisphere**:  _Left_ or _Right_ is more intuitive for the experimenter and could be used to check if the values from the manipulator are correct and flag or inform the experimenter if that information is conflicting.   
2. Adding the "intended location" of recordings from needlesGUI. Instead of writing coordinates, it could be just writing values for _coronal_index_ _sagittal_index_ that should be unique for every recording site defined in NeedlesGUI. So using these two could be used to search for "intended coordinates" in Needles

**Comment by nbonacchi** [comment]
Hi @karolinasocha 
For point 1. if you hover with your mous on top of the label of the coordinates you get exactly that
![hover_action](https://user-images.githubusercontent.com/7206665/75036625-38107e80-54aa-11ea-9a78-3d3dfb376228.png)
