### ISSUE TITLE
calibration results not updated on Alyx

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#316]
When running the frame2ttl calibration I get the warning `could not update board params on Alyx. Saved locally`.

This happened after updating to 6.4.0

**Comment by nbonacchi** [comment]
Is this on all the rigs?
Can you paste the full message displayed in the command prompt?

**Comment by anne-urai** [comment]
![img_20200303_131933 217](https://user-images.githubusercontent.com/6636245/75811517-91a26400-5d5a-11ea-9f06-5555afd84aa9.jpg)

**Comment by nbonacchi** [comment]
Is this on all the rigs?

**Comment by anne-urai** [comment]
at cshl yes, after updating to 6.4.0

**Comment by noamroth** [comment]
I have only set up one rig so far, but I am getting the same error

![image](https://user-images.githubusercontent.com/39137729/76468574-84642580-63a9-11ea-8bf6-9b98ebb27b25.png)
