### ISSUE TITLE
Indicate First/Second screen for display only in 1 file

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#319]
When the display (First/Second) is incorrectly specified, the visual stimuli will show on the main screen instead of the iPad. While the software instructions say this just needs to be listed once in `shader.config`, it looks like each Bonsai workflow in `iblrig/visual_stim/task` separately requires this indicated.

See also https://int-brain-lab.slack.com/archives/CEM70EXTN/p1570733292007600. Could there be just one place where this info is listed, that is shared across tasks?

**Comment by nbonacchi** [comment]
Unfortunately, this is not possible. Every task has its own visual stimulus with the exception of training, biased and ephys. Best would be to figure out a way of fixing it at the system level. In any case the documentation should be updated.
