### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by qas203** [int-brain-lab/iblrig#324]
Hi,

I'm getting the distorted image as shown in the trouble shooting section. I'm trying to follow the instructions to fix this, but I don't have the 'AppleLCD_EDID' file on my computer. I am not sure where to find this file. Can I download this file?

Thank you!

**Comment by moraogando** [comment]
Hi there, I'm having the same issue with one screen, is this file something that can be uploaded to the ilbrig repository? 
Thanks a lot!

**Comment by nbonacchi** [comment]
Here you go it's on develop for now... 
https://github.com/int-brain-lab/iblrig/blob/develop/devices/screen_calibration/AppleLCD_EDID.txt

**Comment by moraogando** [comment]
Oh thank you so much!
This super helpful! ((On top of the whole library, which is a fantastic
toolbox))

Have a great weekend :)
