### ISSUE TITLE
Pybpod v6.4.0 unable to transfer data

### ISSUE THREAD

**Issue by BexTerry** [int-brain-lab/iblrig#328]
nothing seems to happen when I attempt to transfer the data after the update
![image](https://user-images.githubusercontent.com/55093069/75465225-39e1b280-5980-11ea-985c-b22056f96669.png)

**Comment by nbonacchi** [comment]
Hi @BexTerry for some mysterious reason the output of the transfer suddenly stopped working. The transfer should still be happening, in the interval between you press Enter and the command prompt reappears. I'll tag this and see if I can fix it for the next release.
