### ISSUE TITLE
STIM PROB during ephys sessions does not display real probability

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#330]
When running an ephys session today (session 3) I noticed that even though the stimulus appear with consistent probabilities for a block (I guess this makes sense since the ephys session are premade), on the terminal the stim probability output switches every trial between 0.8 and 0.2. As I said this does not appear to be the real probability.

**Comment by anne-urai** [comment]
Related (but thought this was fixed): https://github.com/int-brain-lab/iblrig/issues/297

**Comment by nbonacchi** [comment]
Its fixed yes, he generative probability is being saved properly it's just the display in the command prompt that is wrong...
