### ISSUE TITLE
Delay in animal weight/water amount uploading to alyx

### ISSUE THREAD

**Issue by BexTerry** [int-brain-lab/iblrig#334]
I only have this issue with one animal (KS038) over the past two days. When training is finished, alyx does not have the animal weight and water information. This happened yesterday, and I periodically checked for the next couple of hours if it had updated (it didn't). 

This morning, yesterday's weight and water is there, so it did update at some point in the afternoon, but today it hasn't uploaded to alyx after training again. So there seems to be a huge delay in alyx getting the data for this one animal? (the weight is currently there for today as I manually entered it).

**Comment by karolinasocha** [comment]
this has now also happened for KS039 in a different rig, and 38 is still having this issue every day

**Comment by BexTerry** [comment]
I have now had this issue for another mouse on a different rig (KS039) and KS038 still has this issue every day
