### ISSUE TITLE
Modification of GaborHabituationTask 

### ISSUE THREAD

**Issue by nyquist2x** [int-brain-lab/iblrig#338]
I am just getting started with Bonsai. Our lab purchased the International Brain Laboratory behavioral rig recently and want to modify the original GaborHabituationTask a bit. 

I would like to modify this workflow a bit and add a rectangle in the middle of the screen. Then after a couple seconds, this rectangle will appear on top of the grating pattern (the grating pattern won't move to the center but rather stay in its initial position). 

The problem I have at the moment is this grating pattern is created using a shaders.config file which uses .vert and .frag files  and not the nodes from the BonVision toolbox. I don't think it's possible to make the modification I want using just BonVision nodes, right? It seems that in order to make this modification, I would have to create separate .vert and .frag files for this rectangle and somehow make it compatible with the existing grating pattern shader.config file. 

What is the best way to do this? Thank you.

**Comment by nbonacchi** [comment]
Hi @nyquist2x 
Indeed, the habituation protocol is using a different workflow, the BonVision package was being developed at the same time we were developing our task. Eventually, I managed to refactor the main stimulation workflow used by all other IBL tasks but I never came round to updating the habituation one.

Theoretically it should be possible to use the same workflow, it works as a kind of service launched by python that receives commands from bpod through the Rotary Encoder (RE) serial port connection (yes I know it's weird, we're working on this also), the commands are pretty straight forward it receives a: 
1 it hides the stim (setting the contrast and alpha to 0); 
2 will set the contrast to the value stored from the bonsai.send_trial_info() command (this is sent in between trials)
3 will 'close the loop', i.e. start moving the stim with the positions that are being streamed by the RE
4 will 'open the loop', i.e. effectively freezing the stimulus to its current position on hte screen.

For the habituation protocol the closed loop part is not used so the workflow has a different code where sending a 3 means show in the center, I really should just add this functionality to the main stimulus workflow but I just haven't had the time to do so.

Feel free to take a stab at it, it should be just adding an extra branch in the RE source node and forcing the stim to be presented in the center (and flipping the sync square), then you just need to create a message in python (like the others) say with number 5 and using this as an output in the state that triggers the stim to be presented in the center. Finally, you'll need also to change the bonsai module to use the correct workflow.

Alternatively you can try creating a whole new workflow from scratch so you can get used to Bonsai and the BonVision package. If you're not part of the forums here's a link (https://groups.google.com/g/bonsai-users) this is where most of the Bonsai support is done, we also have a discord server, here (https://discord.gg/K8jUKH7). 

Hop this helps.

**Comment by nyquist2x** [comment]
Yes this is very helpful. Thank you!
