### ISSUE TITLE
passiveChoiceWorld does not run ephys rig

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#339]
I wanted to run passiveChoiceWorld on my ephys rig yesterday however I got this error message and overall it did not run this protocol.
I cannot understand what could be an issue with this, could it be that I have not run ephysChoiceWorld first, and if I did not, I could run passivechoiceWorld? If this is a case, how I can change this dependency, so these two protocols can run independently? 

![image](https://user-images.githubusercontent.com/32096962/98800654-9bf82000-2408-11eb-96d1-3a1242c9eebc.png)

**Comment by nbonacchi** [comment]
PassiveCW is not able to run as a stand alone atm. It still needs some work to run completely as an independent "task", there were some mention of it in the past but it went nowhere. Of course if it's something that is required for the first pass map I can definitely put in into my backlog.
 
Multiple things are required from the ephys session that are assumed in passive: 
- metadata of its corresponding ephys session, for the data transfer at the end 
- session number to load (ephys and passive are pre generated sessions)
- microphone recording is triggered by the ephys session and untriggered by the passive session, 
- ephys also ensures the cameras are running which passive alone does not do. 

Of course if you run an ephys session right before with no trials (so you input all the metadata, session number, weight etc) and you close it, the passive protocol should run as normal and the data will be saved in the raw_passive_data folder of the ephys session.

**Comment by karolinasocha** [comment]
ok, thanks!

Karolina
