### ISSUE TITLE
Task won't run due to test_mouse error

### ISSUE THREAD

**Issue by BexTerry** [int-brain-lab/iblrig#340]
On one of the rigs (rig3), when I go to run the task for an actual mouse (I was trying to start KS050) it gives me the following error:
![image](https://user-images.githubusercontent.com/55093069/106448189-56347c00-647a-11eb-8c52-5423a3f99243.png)

that test_mouse isn't on alyx, despite not running test_mouse

please help! I'm not sure what has changed to cause it to start doing this.

**Comment by rossant** [comment]
It seems there is an issue with `.iblrig_params.json`
do you know where this file is? Could you locate it and see what's in it? 
cc @nbonacchi

**Comment by nbonacchi** [comment]
**C:\ibrig_parame\.iblrig_params.json**
 
You also probably have a local session with a **cerate_me.flag** file in **C:\ibrig_data\Subjects\_iblrig_test_mouse\???** session subfolder that is trying to register and failing. Deleting that file should omit the error message.

**Comment by BexTerry** [comment]
Hi @nbonacchi 
I found the file in a search of the test mouse subject folder, but it won't let me move or delete it because it 'no longer exists'?
![20210202_073822](https://user-images.githubusercontent.com/55093069/106567713-2cd32900-652a-11eb-9c90-8bce33f59a25.jpg)

This is also the case with rig1. Which shows an error regarding test mouse once training has ended, but doesn't affect me starting training like rig 3 does...
![20210202_073932](https://user-images.githubusercontent.com/55093069/106567777-41172600-652a-11eb-8d85-8924e8b35613.jpg)

**Comment by BexTerry** [comment]
The .iblrig_params.json file on rig 3 is blank!?
![20210202_074758](https://user-images.githubusercontent.com/55093069/106568276-fcd85580-652a-11eb-818d-a3f69f3b3bd5.jpg)

Should I manually type in what should be there or is there a better method of doing this

**Comment by nbonacchi** [comment]
https://alyx.internationalbrainlab.org/admin/misc/lablocation/
This should have a copy of your params file if it ever synched with Alyx...

If your params file is completely empty there is a way of generating a new params files:
Open an ipython console in the iblenv rig environment

```python
import iblrig.params as params
params.ask_params_comports(params.write_params_file(force=True))

```
- **write_params_file** will write a new default params dict and force will squash whatever file is ther already.
- **ask_params_comports** will ask you the various devices  COM ports one by one and patch newly created file

Besides the information on calibration that should be empty the only parameters that require user input are the various devices COM ports. (You can also do this manually by opening the file in an editor and filling them in)

Now you can try to load the file
```python
local_params = params.load_params_file()
# Print it to see if everything looks ok
print(local_params)
# Once everything looks OK this will upload to alyx
params.load_params_file(upload=True)
```

**Comment by BexTerry** [comment]
First I tried pasting the information from alyx into the .json file and got this error:
![image](https://user-images.githubusercontent.com/55093069/106719539-53f92b80-65fa-11eb-9a57-c5f27fe7c6ad.png)

then I tried running the script in ipython and it's having the same issue with something that's in line 32
![image](https://user-images.githubusercontent.com/55093069/106719700-8571f700-65fa-11eb-91f3-37c711a4ec99.png)

**Comment by nbonacchi** [comment]
Try removing the comma at the end of the last line where it says "SCREEN_FREQ_TARGET"...

**Comment by BexTerry** [comment]
ah! thank you, this is now fixed
