### ISSUE TITLE
task will not start - error in decoder.py?

### ISSUE THREAD

**Issue by BexTerry** [int-brain-lab/iblrig#341]
Hi,
This rig has been working with no issues. Nothing should have changed as nothing has been altered but when I try and run the task I get this message:
![image](https://user-images.githubusercontent.com/55093069/108177969-c9d1bc80-70fb-11eb-9725-72d18a316ebe.png)

I've tried comparing the decoder.py file to another rig and it seems exactly the same?

**Comment by mayofaulkner** [comment]
Hi, it looks like this is due to an empty .iblrig_params.json file see this issue #325

**Comment by nbonacchi** [comment]
Did you run a water calibration prior to this happening? I've had reports that somtimes this happens after calibration. I'm looking into it. To recover the info in the file you can go to https://alyx.internationalbrainlab.org/admin/misc/lablocation/ and find your rig info there or get the info for your particular rig using ONE. e.g. `one.alyx.rest('locations', 'read', id='_iblrig_cortexlab_behavior_2')`

**Comment by karolinasocha** [comment]
We did not run any calibration but I found what was causing this issue. For some reason params.json (in the ibl_params folder) file was empty. I copied the content of that file from another rig and changed information about the date of calibration, COM ports, and the name of the rig. The task protocol can be launched again.

**Comment by BexTerry** [comment]
This is very strange, this happened in a different rig before (issue #340 ), why are the parameters files being randomly cleared? Nothing different has happened to these rigs for anything to have changed

**Comment by nbonacchi** [comment]
Added iblrig_params backup file on write on develop: 9c5988c8d83df34412ebab7c2519e8c1a08d6d65
