### ISSUE TITLE
error when I launch Bonsai to calibrate camera

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#352]
After installation iblrig on new computer I cannot lunch bonsai to calibrate camera. I wanted to open setup camera and make sure that I have proper alignment but I got this error message. Camera is connected to the computer (I can see camera preview in FlyCap)

![image](https://user-images.githubusercontent.com/32096962/117814353-1ab90300-b25c-11eb-88c7-af4096570b9e.png)

**Comment by nbonacchi** [comment]
The image you shared looks like the wrong workflow to setup the camera, it looks like the recording workflow launched by the task. For a training rig the setup workflow should look like this:

![image](https://user-images.githubusercontent.com/7206665/117817225-4a1d3f00-b25f-11eb-93c9-939f371eb95b.png)

**Comment by karolinasocha** [comment]
indeed, it was the wrong bonsai script. Thanks!
