### ISSUE TITLE
setup_video error

### ISSUE THREAD

**Issue by nmtimme** [int-brain-lab/iblrig#358]
Hello

I was attempting to calibrate the camera during initial setup. I started Bonsai and loaded the setup_video workflow. However, when I hit play, I received the following error:

![image](https://user-images.githubusercontent.com/38138179/118869989-0dcb8d80-b8b4-11eb-9c12-9485a0ff3d95.png)

I'm wondering if this has to do with the version of FlyCapture2 that I installed. The IBL instructions say to install both the 32 bit and 64 bit versions of version 2.12.3.2. On FLIR's website, I was only able to find version 2.13.3.61. I installed both the 32 bit and the 64 bit. I would appreciate any suggestions you could provide. Thanks!

~Nick

**Comment by oliche** [comment]
For posterity, this is ongoing here:
https://github.com/bonsai-rx/bonsai/discussions/1283
