### ISSUE TITLE
ITI length drift over session

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#363]
Main cause is plotting during dead time.
Proposedsolution subprocess plot on raw data instead of accumulating buffers in memory
working prototype in iblrig/feature/async_plots
int-brain-lab/iblrig@f2207367ef707bc5875d095281305e3134213210

Consider Incorporating plotting improvements from #175

**Comment by oliche** [comment]
Fixed in iblrigv8
