### ISSUE TITLE
Frame2TTL SerialTimeoutException

### ISSUE THREAD

**Issue by ludo67100** [int-brain-lab/iblrig#373]
Hi, 
I get the following issue while trying to calibrate the Frane2TTL. It's correclty placed at the bottom right corner of the iPad screen, I can see a small white square behing it.
![write_timeout](https://user-images.githubusercontent.com/44300957/145905411-63e32a6a-d565-4d5c-b6f7-76a9051bb5ce.png)

Thanks, 
Ludovic

**Comment by nbonacchi** [comment]
The socket error seems to indicate you have a concurrent Bonsai process open at the same time.
The serial connection seems to be either a wrong COM port or the device needs resetting.

**Comment by ludo67100** [comment]
Thanks for the reply.
Socket error was solved by manual kill of the Bonsai task. 
We double checked the COM port (through Device Manager and USBTreeView) and specified this corresponding port to the software, however the serial connection error is still there. Do you know how to reset the bpod ?

**Comment by nbonacchi** [comment]
Resetting Bpod from the COM port point of view is just a matter of disconnecting the USB cable and reconnecting it...
to really reset it if you can't reach the teeny board reset button just also unplug the power. Usually, the USB is enough though and using the Pybpod interface you can select the board and press on the `Load board info` button (on the right-hand side) to see if bpod responds with its current config, this should leave Bpod in the same state as resetting it.

**Comment by ludo67100** [comment]
Ok, we managed to reset the Bpod, restarted the computer and now the following error appears. What should we do ? does deleting the .json will generate a new one ?

![jsondecoderIssue](https://user-images.githubusercontent.com/44300957/149599237-2eea759d-9404-4be8-affa-33c2706406ea.png)
