### ISSUE TITLE
5. Contrast probability (branch: none)

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#378]

**Comment by GaelleChapuis** [comment]
Proposal document: 
https://docs.google.com/document/d/1UnuzdzgexBqGZs14YD_VFRJumTqC21AjVmvEQBcd2H4/edit

**Comment by GaelleChapuis** [comment]
To define in a generic fashion when a laser stimulation appears during the task in meta parameters, I think you'll need to define:

- an **anchor time point** (e.g. trial start), 
- a **delay** compared to it (positive necessarily, e.g. +100 ms ; which would mean +100ms after trial start), 
- a **polarity** (e.g. the laser is OFF and will be turned ON during this period), 
- and a **duration** (e.g. laser switches polarity for 300ms)

(this is assuming only 1 pulse is given per trial - you might want to think/ask if more are needed!)
