### ISSUE TITLE
9. remove ibllib/ONE lib dependency -> migrate all rig related code to iblrig (branch: migrate_ibllib_fucs)

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#382]

**Comment by nbonacchi** [comment]
Also **rename iblenv to iblrig** in rig env, test for installation and migration from iblenv installed rigs...

**Comment by nbonacchi** [comment]
tests/test_ibllib_imports.py
def test_iblrig_imports(self):
        # List of all import statements in iblrig on dev 20200609
        import ibllib.graphic as graph  # noqa
        import ibllib.io.flags as flags  # noqa
        import iblutil.io.params as lib_params  # noqa
        import ibllib.io.raw_data_loaders as raw  # noqa
        import ibllib.pipes.misc as misc  # noqa
        import one.params as oneparams  # noqa
        from one.api import ONE  # noqa
        from ibllib.oneibl.registration import RegistrationClient  # noqa
        from ibllib.dsp.smooth import rolling_window as smooth  # noqa
        from ibllib.graphic import numinput, popup, strinput  # noqa
        from ibllib.io import raw_data_loaders as raw  # noqa
        from ibllib.misc import logger_config  # noqa
        from ibllib.pipes.purge_rig_data import purge_local_data  # noqa
        from ibllib.pipes.transfer_rig_data import main  # noqa

**Comment by micheleangelofabbri** [comment]
Branch for this issue: https://github.com/int-brain-lab/iblrig/tree/remove_ibllib_dependencies

**Comment by micheleangelofabbri** [comment]
Pull request for this issue: https://github.com/int-brain-lab/iblrig/pull/394
