### ISSUE TITLE
Overlay white border on camera image for training rig

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#395]
In the ephys rig, at the start of a session the white overlay (showing the borders of the holder etc) appears onto the video display (which is very useful to correct for the positioning of the camera).
In the training rig however, there is no automated launch of such display (the user has to manually launch the camera calibration).
For the training rig, would it be possible to acquire the video data, and have the white borders marking the holder etc overlaid onto it during the behavior session (without affecting the raw data collection)?

**Comment by micheleangelofabbri** [comment]
This will be looked into during the week of 2022-02-14.
