### ISSUE TITLE
Bpod Error Exception 

### ISSUE THREAD

**Issue by srhaiken** [int-brain-lab/iblrig#398]
Over the past few days, one of our rigs randomly quits out mid-task and an error reading this pops up:

Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 227, in <module>
    if not bpod.run_state_machine(sma):  # Locks until state machine 'exit' is reached
  File "c:\users\quinn\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 279, in run_state_machine
    raise BpodErrorException('Error: The last state machine sent was not acknowledged by the Bpod device.', self)
pybpodapi.exceptions.bpod_error.BpodErrorException: ('Error: The last state machine sent was not acknowledged by the Bpod device.', <pybpodapi.bpod.Bpod object at 0x000001A3D9F19688>)
System.InvalidOperationException: Sequence contains no elements.

I've tried different ports, cables, and bpods, to no avail. Any suggestions?

**Comment by nbonacchi** [comment]
Hi @srhaiken 
This usually happens if the communication between Bpod and the computer fails, please verify your USB cable and the USB connector on the Bpod device.
Other possible causes can be some short circuit or improperly connected cable of something connected to the Bpod, and I've seen this also happen as a consequence of power fluctuations/surges from the electrical outlets at the wrong moment.

**Comment by srhaiken** [comment]
I am confident that everything is connected properly, and every time I switch the USB cable, it works for a day or so and then the same issue arises. Is there something that frequently causes short circuiting that maybe I need to pay more attention to?

**Comment by nbonacchi** [comment]
If you swapped everything out already and the issue still happens I would
reset the computer. Fresh install of everything including Windows. We had
some issues with some Windows updates that leave the PC in a weird state
but I've never seen the specific issue you're describing with your level of
consistency.

**Comment by srhaiken** [comment]
I was looking through Github for similar issues and one from March 6, 2019 talked about C:\iblrig_params\.bpod_comports.json however that is a file I do not have
