### ISSUE TITLE
Update NYU ephys rig from v6.4.2 to v6.5.3

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#403]
Ephys rig at NYU currently sitting on a deprecated version of the iblrig software. Issue first reported on 2022-03-08. End user attempted to perform resolution on their own, but was unable to upgrade. Teamviewer credentials were provided near the end of the day. 

To continue investigating, attempts to connect to the teamviewer session were made on 2022-03-09. The connection was unable to be established b/c the software was not running or the machine was reboot.

Terminal output provided by end user:
```
(base) C:\iblrig>git reset --hard
HEAD is now at 1856927 Merge branch 'release/6.5.3'

(base) C:\iblrig>git fetch --all
Fetching origin

(base) C:\iblrig>git pull origin master
From https://github.com/int-brain-lab/iblrig
 * branch            master     -> FETCH_HEAD
Already up to date.

(base) C:\iblrig>git checkout tags/6.5.3
HEAD is now at 1856927 Merge branch 'release/6.5.3'

(base) C:\iblrig>git status
HEAD detached from 6.4.2
nothing to commit, working tree clean
```

Awaiting feedback from user before attempting to investigate further.

**Comment by nbonacchi** [comment]
You forgot to `git pull`

**Comment by micheleangelofabbri** [comment]
@nbonacchi the `C:\iblrig>git pull origin master` is in there, no?

---

I was able to look at this machine today and performed the following:
* mapped the Y:\ drive to - \\#.#.#.#\ibldata
* backed up and renamed C:\iblrig directory
* backed up C:\iblrig_param directory
* completely removed anaconda, deleting the various hidden folders as well
* `C:\>git clone https://github.com/int-brain-lab/iblrig.git`
* `C:\>cd iblrig`
* `C:\>git checkout tags/6.5.3`
* `C:\>python install.py`
* ran through the installation
* ran pybpob with the habituationChoiceWorld successfully as the test user on the test subject
* Cleared out the C:\Users\IBLuser\.conda\environments.txt to get a proper environment listing from `conda env list` command

**Comment by nbonacchi** [comment]
Yes, it's there, probably too many times :smile:
