### ISSUE TITLE
rig cleanup script

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#416]
From a slack convo:
There was a script called purge_rig_data.py that accepted a folder and a filename. It looked for all those filenames in the folder and checked if the files exist on alyx/flatiron, if yes deletes them.
Unfortunately I just checked and the script no longer works after the latest ONE changes in search and cache files. It should be refactored to also use the local server to check if the file can be safely removed from the rigs and should work for all modalities.

**Comment by micheleangelofabbri** [comment]
Corrected in v6.6.4 release
