### ISSUE TITLE
Behavior computers with 2 HD params data folder not used

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#418]
Photometry rigs have 2 HD one NVME M.2 boot drive with 500Gb and one SSD of 1TB

C: is mapped to the 500Gb drive
D: is mapped to the 1TB drive.

path helper.get_iblrig_data_folder recapitulates the logic of finding iblrig and defining the data folder from that iblrig folder.
It should first check the params folder and use DATA_FOLDER_LOCAL 's value. if value is None then define the default location from where the iblrig folder is.

This was never a problem before as training/behavior rigs only have one HD

**Comment by micheleangelofabbri** [comment]
path_helper now obtains path information from an iblrig_params.yml file in the root directory; entries can now be specified by end user.
