### ISSUE TITLE
Install tries to use mamba even if not installed

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/iblrig#419]
**Describe the bug**
Installation uses mamba regardless if it's installed: https://github.com/int-brain-lab/iblrig/blob/603c5a21a4a9e560532815c0cb0626ce7ebdedaf/iblrig/envs.py#L13

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by juhuntenburg** [comment]
I realize this is probably on purpose since the install script is supposed to install mamba, but in our case mamba didn't work so we tried to use conda and got stuck of a bit until we realized that for this script mamba is hardcoded. Not sure what is the best solution, just wanted to leave a pin

**Comment by juhuntenburg** [comment]
Fixed in #422

**Comment by micheleangelofabbri** [comment]
Mamba dependencies have been completely removed.
