### ISSUE TITLE
Environment is not created and no error raised

### ISSUE THREAD

**Issue by juhuntenburg** [int-brain-lab/iblrig#421]
This line does not seem to be properly executed. No error was raised, but the environment path was still None afterwards. When running the create command from the command line it works.
https://github.com/int-brain-lab/iblrig/blob/master/install.py#L167

**Comment by juhuntenburg** [comment]
Same issue for this line:
https://github.com/int-brain-lab/iblrig/blob/master/install.py#L167

**Comment by juhuntenburg** [comment]
Fixed in #422

**Comment by micheleangelofabbri** [comment]
Install script has officially been removed from the installation procedure in favor of detailed instructions.
