### ISSUE TITLE
Question about Altering Task Code

### ISSUE THREAD

**Issue by icullen87** [int-brain-lab/iblrig#424]
Hi, 
I am trying to alter our task code to include other parameters and other modules not currently in line with BPOD, but am getting quite confused about what files need to be altered for this new task (such as file locations within code, environments, etc). Any advice or more direction would be very helpful!

**Comment by micheleangelofabbri** [comment]
Direct communication via email/zoom has been established and troubleshooting efforts have been in full swing.
