### ISSUE TITLE
Chaining different protocols or running the same protocol multiple times

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#429]
**Description**
Be able to run multiple protocols, one right after the other. Determine how to assign session numbers and appropriate data extraction methods. Potentially to add extractor names directly into the experiment description file.
* Spacers between protocols : implement in each task
* Extractors to take into account these spacers
  * One extractor to read in spacer times, and send to following extractors (per protocol)
  * Following extractors to use spacer times: chunk + generate timestamps for events
* Extractor to save into correct collection
* Where to save output (folder structure, how to concatenate different runs of same protocol etc)

**Requirements**
Experiment description file formatted in a way to be able to properly extract the data afterwards

**Measure of Success** 
Running a full set of tasks, automated alyx registration, upload to local lab server, and perform extractions

**Comment by GaelleChapuis** [comment]
- Chained protocol branch
- use Guido's test session (runs 2x passive)

- define folder architecture (each go in folder, decide on collection name)
- ensure save trials data into collection (/alf/task00) -> change extractor so they have input argument of where to save (atm behavior hardcoded everywhere)

**Comment by oliche** [comment]
cf. oddBall protocol on Alyx that implements a chained protocol with spacers.
iblrigv8 GUI offers the functionality
