### ISSUE TITLE
Trial parameter generator ; task parameterization

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#430]
**Description** 
Create class that concatenates session / trial parameters (set at high-level by user, e.g. what distribution type to use fo contrast set drawing) ; and output trial-based values (e.g. what contrast is used on trial X)

**Measure of Success**
Run ephysCW with ephysCW prob for contrast set and biasCW prob for contrast set ; for 1000 trials ; check the contrast distribution output is what is expected
Run MOCK session several times; check each is using different trial sequence

**Comment by micheleangelofabbri** [comment]
Slack conversation regarding issues when running MOCK sessions - https://int-brain-lab.slack.com/archives/CEM70EXTN/p1666969709195399

**Comment by GaelleChapuis** [comment]
- Specifications: follow documentation but documentation may be wrong - test using previous sessions
- Changes needed on (priority): MOCK (ephys) ; ephys ; biased ; training ; habituation (note: training is adaptive)
- PassiveCW
- Where are params stored? On local drive ; does not go onto other rig (problem as users cannot change rig) -> could store onto local server instead of rig

**Comment by GaelleChapuis** [comment]
12-Dec-2022:
- Gather data for each type
- pick one task (biased)
- Run on local rig, make list of param / setting / variable

**Comment by micheleangelofabbri** [comment]
List of parameter and setting files:
- `C:\iblrig\iblrig_params.yml` - used to set various directory locations, created to more easily test on various different systems; introduced in v7
- `C:\iblrig_params\.iblrig_params.json` - used to set board name, rig version, com ports, and other hardware related information
- `C:\iblrig_params\user_settings.py` - used to set various pybpod/pyforms options
- `C:\iblrig_params\IBL\tasks\_iblrig_task_name\_iblrig_task_name.json` - mostly used to set all of the pre/post commands for a task, these get executed by pybpod as subprocess or popen
- `C:\iblrig_params\IBL\tasks\_iblrig_task_name\session_params.py` - houses the SessionParamHandler class, imports user_settings and task_settings, calculates other secondary session parameters, runs Bonsai and saves all params in a json settings file
- `C:\iblrig_params\IBL\tasks\_iblrig_task_name\trial_params.py` - houses the TrialParamHandler class, all parameters for the current trial, on self.trial_completed a JSON serializable string containing state/event data and all the parameters is returned to be printed out and saved by pybpod under the stdout flag, self.next_trial calls the update functions of all related objects
- `C:\iblrig_params\IBL\tasks\_iblrig_task_name\task_settings.py` - used to set various 'configurable' task values, includes a mixture of hardware, reward, ITI, and stim probability information

**Comment by micheleangelofabbri** [comment]
After some finagling of system paths and module imports, we were able to obtain Session Param Handler and Trial Param Handler values at the beginning of the 4th trial of biasedChoiceWorld.

[tph.txt](https://github.com/int-brain-lab/iblrig/files/10236471/tph.txt)
[sph.txt](https://github.com/int-brain-lab/iblrig/files/10236473/sph.txt)

**Comment by micheleangelofabbri** [comment]
Issue being closed and moved to a GitHub Project
