### ISSUE TITLE
Use description file in all experiments (transition fully to dynamic pipeline)

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#431]
**Description**
Be able to utilize the experiment description file in all experiments. Determine the best way to generate the file. 

**Requirements** 
GUI or command line interface for generating 

**Measure of Success**
Session registration to use project and procedure from experiment description file

**Comment by GaelleChapuis** [comment]
GUI to add procedures (ATM from behavior PC):
- [ ] Decide how users would launch GUI (instructions vs in code) -> add GUI  to video / ephys prepare script ?
- [ ] Change inputs to GUI (session path, mouse name etc)
- [ ] Save what last description file was ; for first session: blank -> Create template users can load
- [ ] Create documentation on how to launch GUI / make it more user friendly

- [ ] Use project / procedure when registering session

**Comment by GaelleChapuis** [comment]
12-Dec-2022:
- Walk through GUI
- See what can be made more user friendly
- Change inputs (mouse name etc)
