### ISSUE TITLE
Guideline for users to change the task parameters

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#432]
**Description** 
Once Task restructuring has been settled upon, write up documentation for end users

**Requirements** 
Task restructuring and experiment description file generation 

**Measure of Success** 
Have experimenter run through documentation unassisted and ensure they are able to change task parameters

**Comment by GaelleChapuis** [comment]
- [] Check compatibility break with other existing task (from personal projects especially)

**Comment by GaelleChapuis** [comment]
12 Dec 2022:
- Round up of existing tasks
