### ISSUE TITLE
IBL Bonsai Does Not Work With Windows 11

### ISSUE THREAD

**Issue by icullen87** [int-brain-lab/iblrig#435]

**Comment by micheleangelofabbri** [comment]
At the moment Windows 11 is untested and not supported. Could you provide more details on your environment and what error you received so that we know what to look out for in the future?

**Comment by icullen87** [comment]
Whole task will run, and start, but bonsai won't. I will have to test it tomorrow and let you know.

**Comment by oliche** [comment]
It does
