### ISSUE TITLE
behaviour training rig no longer detects screen

### ISSUE THREAD

**Issue by avmcb** [int-brain-lab/iblrig#441]
PC froze mid session with no way to release the freeze without restarting PC (mouse keyboard everything froze). Upon restarting the visual stimulus appeared on wrong screen but without a screen switch (desktop did not appear on ipad). Display settings checked and ipad screen was not detected. 

Checked hardware, all looked ok but replaced with new screen, board and cables to make sure. No effect had, still no detection of ipad screen on the rig. 

Have attached device manager screenshot with monitor open as requested. 

![device manager_screensht](https://user-images.githubusercontent.com/79155200/220123703-00521809-f8b0-4581-8b1a-24efbd4c3c72.PNG)

**Comment by oliche** [comment]
Monitor was detected again by the OS.
