### ISSUE TITLE
Multiple Camera Frame Rates Question

### ISSUE THREAD

**Issue by nmtimme** [int-brain-lab/iblrig#452]
Hello

I noticed in the IBL ephys rig that three cameras are run at different frame rates. What is the motivation behind doing this, rather than having all three run at the same frame rate? Thanks!

~Nick

**Comment by mschart** [comment]
Hello, We chose the left cam to have half the temporal resolution (60Hz) but full spatial resolution while the right cam has 150 Hz but half the spatial resolution. So we got high spatial or high temporal resolution - as we couldn't have both for hardware acquisition reasons (e.g. dropping frames, too much data).

**Comment by nmtimme** [comment]
Thank you for that information! That clarifies things perfectly. Have a good day!
