### ISSUE TITLE
Updating plots with more details

### ISSUE THREAD

**Issue by kimiline** [int-brain-lab/iblrig#475]
Could graph plots contain information including:
mouse name
weight
the task being run

Can they also include details omitted from iblrigv7, such as: 
details on blocks
~~number of trials run
total water delivered~~

It would also be very helpful to add vertical and horizontal lines on graphs (at least x = 0 and y=0.5 on psychometric curve, y= 0.5 on RT).  

Thank you!

**Comment by oliche** [comment]
Add a screenshot

**Comment by bimac** [comment]
https://github.com/int-brain-lab/iblrig/releases/tag/8.12.4
