### ISSUE TITLE
valve calibration

### ISSUE THREAD

**Issue by bimac** [int-brain-lab/iblrig#486]
See #483

@noamroth:
> We need a way to do water calibration, currently this isn't an option as far as I can tell?

@lafresil:
> Water/Frame2TTL calibration

**Comment by bimac** [comment]
Both water and frame2ttl calibration are very high on our todo-list - this will be added soon

**Comment by samupicard** [comment]
@bimac is this still high on the todo-list or has it been bumped down? Need to do calibrations soon on a rig that doesn't have v7 installed, and i was hoping i wouldn't need to specifically for this purpose...

**Comment by bimac** [comment]
yes, it is - right after copy-scripts and stub-creation

**Comment by samupicard** [comment]
5 months in and still no valve calibration. Could we have a realistic estimate please?
