### ISSUE TITLE
legend for biasedChoiceWorld block lines

### ISSUE THREAD

**Issue by bimac** [int-brain-lab/iblrig#487]
See #483

@noamroth:
> biasedChoiceWorld block lines need a legend (which color corresponds to which block?) It would also be nice if the current block type was written somewhere, but this isn't absolutely necessary.

@lafresil:
> Legend of the graphs of the biased protocol. I would assume, by default, that the orange graph is the 50/50 probability but the rest I don't know. The current block type is also helpful to know.

**Comment by noamroth** [comment]
Hi @bimac, looks like in the current version the block lines are now all the same color - could you please make them back to different colors (and then add a legend somewhere)? Generally the plot updates look really good, but for this specifically unfortunately now it's even harder to tell which block the mouse is on...

**Comment by bimac** [comment]
whoops. my bad. fixed with da5556fe - will be pushed out with 8.12.7 today.
