### ISSUE TITLE
colored background screens go away after some number of trials

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblrig#501]
I noticed that in iblrigv8, sometimes that colored background screen (e.g. yellow) goes away after a few trials. Perhaps this is because motion was suddenly detected, but this is not how it was configured in all of the previous versions of the task so we should probably stay consistent  (at least while people are still training/recording for brainwide map). Previously, once a screen appeared, it always remained that color (and the message in the terminal kept coming up on every trial) until the end of the session.

**Comment by oliche** [comment]
Taken care of in 6ed33e2b3f8f88f01e1db91aec2f9ea7905c1223 !
