### ISSUE TITLE
transfer_data fails with calling without paths

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#514]
See https://int-brain-lab.slack.com/archives/C05MDMWNPV1/p1695985998054789

**Comment by k1o0** [comment]
While this is being released as a HOTFIX users should be able to transfer data by calling `transfer_data` from the command line with the local and remote paths as input, e.g. `transfer_data C:\iblrigv8_data W:\`.  @bimac please confirm this is indeed the case.

**Comment by bimac** [comment]
No, I'm afraid this is not yet the case - will add an argparser later today

**Comment by bimac** [comment]
[0a2a879](https://github.com/int-brain-lab/iblrig/pull/517/commits/0a2a87956b0df2c644f2a56e2a7312f9ca393640)
