### ISSUE TITLE
rework UI for signing into Alyx

### ISSUE THREAD

**Issue by bimac** [int-brain-lab/iblrig#518]
- pre-populate selection field with all lab-members
- user/password entry (https://github.com/int-brain-lab/iblrig/issues/569)
- fix issue with sudden switch of user-name

**Comment by samupicard** [comment]
@bimac final point here would be particularly good to fix soon, it's causing regular errors atm

**Comment by samupicard** [comment]
@bimac this is continuing to cause issues, a fix would be really appreciated!
