### ISSUE TITLE
frame2ttl - screen calibration

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#52]
Is there currently integration with the Bpod frame2ttl? it would be great if there is 'setup' script for running tests on o.a. the screen timing and screen calibration. Should the task script run a quick test of the frame2ttl before starting?

**Comment by nbonacchi** [comment]
The rig assumes a frame 2ttl is connected to BNC1 input.
Clibration test of frame2ttl probably need only to be done once... I'm working on a script to calibrate it, not inside pybpod but that is run on its own with a sweep of colors to the screen RGB. I need to access the analog data from the serial port for that... 

From Josh, for reference:
The interface is super-simple - open a USB serial port with PySerial, write character 'V' (byte 86), then read the current sensor value as a 32-bit unsigned int. I'd loop that code to get a few values for each point if you find it to be noisy at different pixel intensities.
The sensor encodes light intensity as frequency of logic switches (high->low OR low->high), so value you're reading is the time between the most recent transition and the previous transition in microseconds. How this value relates to light intensity depends on frequency according to Fig. 10 here: http://ams.com/documents/20143/36005/TSL235R_DS000120_3-00.pdf

**Comment by nbonacchi** [comment]
cycle through all values of R, G, and B
measure value with photodiode (figure out how to read into pc the analog values from photodiode BNC output)
plot curves, find 0.5 value for R,G,B
use as vec4(RGB/3 + vec3(Rgaussiangrating, Ggaussiangrating, Bgaussiangrating), 1.0)

**Comment by GaelleChapuis** [comment]
Can we have a user feedback upon the run of the calibration in pybpod?

**Comment by GaelleChapuis** [comment]
Deadline 7th Feb possible?
