### ISSUE TITLE
Contrast set error after moving to training phase 5

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#529]
When going from training stage 4 to 5, the 50% contrasts are supposed to disappear on both sides. However, in recent sessions from one mouse we noticed that the left 50% continued to appear while the right had disappeared. Plots attached showing 'signed' contrast over trials, for the most recent session and for the session where this problem apparently started.

![image](https://github.com/int-brain-lab/iblrig/assets/25370956/6b2112fa-37f9-44fb-8e98-58df96d8a756)

![image](https://github.com/int-brain-lab/iblrig/assets/25370956/9145fcee-e6dc-4734-b18b-71c9419aacd3)

Assuming this is a bug (not some hidden debiasing feature). If so, could you investigate and correct asap?

**Comment by bimac** [comment]
which subject is this?

**Comment by samupicard** [comment]
SP046, from Oct 11th to 17th. The session paths of the example plots are in the figure titles.

**Comment by bimac** [comment]
whoops, sorry, didn't see the titles

@oliche

**Comment by oliche** [comment]
Ok this applies to training CW, 0 contrasts get overwritten with another draw of all contrasts with uniform probabilities.

#530 fixes the issue.

Please update to 8.11.3 !
