### ISSUE TITLE
Incorrect task duration time

### ISSUE THREAD

**Issue by BexTerry** [int-brain-lab/iblrig#534]
After the first trial on training_choiceworld, the 'time elapsed' at the top of the live plot jumps from 0 to '-1 days' and a seemingly random hours and minutes count.

I didn't notice until halfway through SP046's session but once I removed him I ran a test on the same rig and this bug still occurred.

**To Reproduce**
1. On the latest version of iblrigv8
2. Run training_choiceworld 

![20231024_155009](https://github.com/int-brain-lab/iblrig/assets/55093069/ca631b77-f6d8-4d35-8463-99fc2eebda95)
![20231024_155645](https://github.com/int-brain-lab/iblrig/assets/55093069/097d9281-7a7e-4909-afd7-4a7464b85f95)

**Comment by bimac** [comment]
fixed in [9028176](https://github.com/int-brain-lab/iblrig/pull/533/commits/902817655b9f6df40b6fd139ba4dd667f24af882)
