### ISSUE TITLE
Extraction for trainingPhaseChoiceWorld not working

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#540]
Automated extraction for `iblrig_tasks_trainingPhaseChoiceWorld` isn't working atm, despite the fact that the standard extractors are written into the [task](https://github.com/int-brain-lab/iblrig/blob/53df8f066576ed2ac8a0e0ec719a73175a6e7f8e/iblrig_tasks/_iblrig_tasks_trainingPhaseChoiceWorld/task.py#L13)
Is this a code bug or is something wrong on my end?

_Originally posted by @samupicard in https://github.com/int-brain-lab/iblrig/issues/536#issuecomment-1785164758_

**Comment by k1o0** [comment]
- [x] SP046\2023-10-27\001
- [x] SP046\2023-10-31\001
- [x] SP046\2023-11-01\001
- [x] SP046\2023-11-02\001

**Comment by k1o0** [comment]
One https://github.com/int-brain-lab/ibllib/pull/647/commits/276603eb1cb50197415897ea1795a806182ded68 reaches master we can extract these sessions as normal.

**Comment by k1o0** [comment]
Set the behaviour tasks to waiting. Here are the task IDs:
```
6194d393-0d6b-4efd-a947-4606d0a60371
4aba12a0-5745-4460-bfa4-063ed7c83237
a6ce4bcc-8c35-4ac6-a983-b9eda5da16d4
f8a19f7c-616b-4bfd-b819-2970d8398374
```

**Comment by k1o0** [comment]
It appears that all the tasks have completed without error.
