### ISSUE TITLE
Habituation trial intervals should have correct event order

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#549]
The Bpod state machine for habituationChoiceWorld is extremely misleading. The Bpod state machine for this task has extremely misleading names! The 'iti' state is actually the delay between valve open and trial end (the stimulus is still present during this period), and the 'trial_start' state is actually the ITI during which there is a 1s Bpod TTL and gray screen period.  I suggest the following changes:

- [x] Revert commit https://github.com/int-brain-lab/iblrig/commit/b85d4c28e63e29497837c89e9dbc250ea0e59e78 ASAP as the TTL doesn't reflect the ITI and is the same length as the trial_start TTL (and is therefore indistinguishable).
- [x] Rename the states to better reflect their role, and add documentation to the states explaining clearly the purpose of each state and its outputs.
- [x] Modify the state machine so that the Bpod TTLs delineate the trial edges. This would make extraction far simpler, intuitive, and more closely reflect the other task protocols.

**Comment by bimac** [comment]
reverted with 819f8ec88fa7688e6f21b58385062b3520ce486f and released in [8.12.6](https://github.com/int-brain-lab/iblrig/releases/tag/8.12.6)
