### ISSUE TITLE
user error correction: issue a warning if a subject is trained a second time in a day

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblrig#56]
That would be useful for the experimenters handling a large colony.

**Comment by anne-urai** [comment]
Some more suggestions to help the user avoid mistakes:

> hi python devs, I’d like to make some suggestions and open the discussion about user design features that may help reduce, or mitigate the impact of human error. For example, it’s happened a few times that a mouse was run under the wrong number - which messes up things in all sorts of ways… Some ideas
> • check when starting a session if that mouse has already trained today, if yes warn the user
> • check if this mouse has trained on this specific rig before, if yes warn the user
> • come up with a protocol (both on the data side and alyx side) for assigning water/trials/files to a different mouse. this would probably have to be done immediately after/during a session
> • when entering weight, calculate if this is plausible given the mouse’s previous weight - if not, warn the user

**Comment by anne-urai** [comment]
Most probably, mice will always be trained in the same order - check if the order of the mice on this rig matches that of yesterday, if not warn the user
