### ISSUE TITLE
Quantify delays between quiescence period and stim on

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#562]
There have been reports of wheel movements up to 200ms before stim on. This should be quantified by checking the distribution of delays between the end of the quiescence period and stim on to determine if the cause is the state transition or missed frame2ttl pulses (or both).  ~~Currently waiting on eid and trial number with -ve RT.~~

**Comment by k1o0** [comment]
Example trial where movement starts before stim on: eid = e3d1f7da-c4a4-435b-8129-d6312ae94995, trial no: 94

**Comment by k1o0** [comment]
For the above trial the movement occurred after the stim on trigger but before the detected stim on time. I have asked for an example of a movement occurring > 100ms before the recorded stim on time.  I suspect all premature movements after the stimOnTrigger time. Perhaps the firstMovement times should be calculated from the trigger time instead of stim on time - 0.2s?

**Comment by k1o0** [comment]
Looking further into this. `eid, trial = ('a8ff1a94-5f5a-4cf6-87a2-d7fa6e2e4036', 28)` the stim_on state = `[82.186, 82.1861]` whereas the stimOn time from the frame2ttl is `82.1861`. I'm not sure how the state machine appeared to detect the stimulus via the frame2ttl yet the extracted stim on time is much later.  This is a biasedChoiceWorld session acquired at cshl-behavior-bpod2.

**Comment by GaelleChapuis** [comment]
V4 extractor extracted stimOn incorrectly -> see if V5 extractor works
Re-extract V4 sessions (training only) for stimOn to be correct


Advise user not to use V4 for analysis for now

**Comment by k1o0** [comment]
Although there appear to be consistent, spurious sync square changes, and occasions where no update occurs (see below), most incorrect stimulus times could be corrected using improved extraction code. See this milstone: https://github.com/int-brain-lab/ibllib/milestone/1

![Image](https://github.com/int-brain-lab/iblrig/assets/25670666/6ef63ccc-f1a8-43d5-8454-43c4195db096)
