### ISSUE TITLE
investigate stimulus-locked flickering of bpod led (tak to Josh)

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#574]
Fix requires firmware update. Should make sure every is running up-to-date firmware

**Comment by bimac** [comment]
Josh is puzzled about this. All of our Bpods should be on the same firmware-version (v22) but he said that cortexlab might have some earlier models that were re-used for IBL. He is not aware of similar issues having occured elsewhere and suspects that it might be due to a corrupt firmware.
