### ISSUE TITLE
ephys flag

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#60]
If running an ephys session, some things should be different from training:
* the ability to manually stop the session, i.e. no automated disengagement detection
* the ability to pause the trials in case anything needs to be fixed in the rig

**Comment by anne-urai** [comment]
When running ephys, we'll need time to prep everything. Do we already want to start the task, so that we can record audio and video while the mouse is positioned, probes prepared etc?

**Comment by nbonacchi** [comment]
> If running an ephys session, some things should be different from training:
> 
> * the ability to manually stop the session, i.e. no automated disengagement detection
> * the ability to pause the trials in case anything needs to be fixed in the rig

These two features are the default of pybpod... There is a pause button that will pause the state machine, and a stop button to stop the task.

For e-phys I imagine one will want to start the recording system, start the task, pause it, setup the animal and unpause the task. 
Alternatively is the setup takes too long and we don't want to record that much video/ephys that is not used, one could prepare the subject first and then run e-phys and behavior/video
