### ISSUE TITLE
passiveChoiceWorld bugs

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#611]
There are issues when running passiveChoiceWorld using v8.15.1. The task starts normally and the gray screen + sparse noise seem fine, but

- [x] the passive stimuli are not showing (only reward valve and audio cues). The bonsai window doesn't open after shutting down the sparse noise, and there is no sync square either.
- [x] when finished, the pop-up asking whether this is a dud appears, claiming there were 0 trials. This may be related?
- [x] there is no option to select the stimulus sequence to be used, as previously in v7. This may be intentional, but it would be good to know how the stimuli are computed now. If the method is different from v7 the protocol really should carry a different name, and we should have the option to run exactly the same as in v7?

**Additional feature request**
On this note, I also have a feature request: a passive protocol in which we replay the audio and visual stimuli in the same order as the most recent active ChoiceWorld session (training/biased/ephys) - rather than a pre-computed order. The ITIs could still be random and independent of each other, but the order would be the same.

**Comment by bimac** [comment]
We were missing a call to Bonsai. I managed to get the sync-square back, but I don't see the Garbor stim yet. @oliche, do you have an idea? See: branch [hotfix/passive](https://github.com/int-brain-lab/iblrig/tree/hotfix/passive)
