### ISSUE TITLE
Task ITI is 1.5 seconds instead of 0.5

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#617]
[Appendix 2 of the behaviour paper ](https://docs.google.com/document/d/1RA6wgbWfxD2kGlpNxt0n3HVcW4TEIx8e-YO7k_W1pHs/edit#heading=h.h995uxwh6mhn) defines the inter-trial interval (ITI) as the period of grey screen between stim off and the start of the quiescent period of the next trial. This is also known as the closed-loop grey screen period as there is no stimulus and no external stimuli affect the state (i.e. wheel ignored).

The ITI is specified as 0.5 seconds and the QC check asserts this, however the ITI in iblrigv8 is in fact 1.5 seconds. 1 second of grey screen within the state machine, and 0.5 seconds of 'dead time' between state machine exit and the next trial.

**Comment by oliche** [comment]
Fixed in 76a6c625c5d01debd9288c4e6763da65d0f7b801
