### ISSUE TITLE
Chained tasks not properly registered to alyx

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#621]
There seems to be an issue with the way chained protocols are registered on Alyx. If a given session had several chained protocols (e.g. `raw_task_data_00`, `raw_task_data_01`, `raw_task_data_02`) run back-to-back in 'append' mode, this gets listed on Alyx as a session with a single task protocol (the one from `raw_task_data_02`) and with a single reward amount delivery (the one from `raw_task_data_00`).

**Comment by GaelleChapuis** [comment]
Is the same exact protocol ran (in which case it makes sense to save the variables only once), or are these different protocols with different variable values ?

**Comment by samupicard** [comment]
These are usually different protocols (in this case, trainingChoiceWorld, biasedChoiceWorld, passiveChoiceWorld). 
Whether or not this is the case, the water amounts should be added up between protocols.

**Comment by samupicard** [comment]
An issue that is possibly related: the SESSION_NUMBER parameter in the the taskSettings.json is set to '1' for the first task protocol that was run, and then set to '0' for subsequent chained task protocols (and this is preventing extractions from taking place). Instead, they should all be set to the actual session number that the chained protocol falls under.

**Comment by k1o0** [comment]
No response from @samupicard so I've gone ahead and merged the branch into iblrigv8dev for the next release.
