### ISSUE TITLE
Incorrect task sync label in experiment description

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#625]
The task label is hardcoded to 'bpod' which is only correct if MAIN_SYNC is False on this PC:
https://github.com/int-brain-lab/iblrig/blob/27722fae29c27fa5f71598b0e89ac84639442be4/iblrig/base_tasks.py#L296

We would need a way to select the sync label in the GUI and pass it as a standard parameter.

**Comment by chris-langfield** [comment]
Only set to `"bpod"` if MAIN_SYNC is True

**Comment by k1o0** [comment]
Fixed on coms branch
