### ISSUE TITLE
Save pause periods

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#637]
Is there any way to know if a task was paused? If not, there should be: perhaps the task data can include timestamps of when the task was paused. This would be useful in analysis.  It would be usual to document how to determine which trials were paused so they may be discarded.

**Comment by bimac** [comment]
Pressing the pause button will only act inbetween trials. The trials themselves are not affected.

**Comment by bimac** [comment]
[I added some logging](https://github.com/int-brain-lab/iblrig/blob/6f75b803450314a5412d2a8286600f1c3697d6f5/iblrig/base_choice_world.py#L191-L203), not sure how much sense adding this to task-data makes (cf previous comment)
