### ISSUE TITLE
installation of spinnaker uses the default ONE

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblrig#648]
If the default ONE instance on the computer doesn't have access to the s3 credentials, the download fails.

**Comment by bimac** [comment]
put files on public alyx

**Comment by bimac** [comment]
resolved with [19a6ea9](https://github.com/int-brain-lab/iblrig/pull/643/commits/19a6ea90b2b2ebc029803c930b327f644ef2e45b)
