### ISSUE TITLE
advancedChoiceWorld: make reward amount dependent on stimulus side

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#652]
Would it be possible to change `_iblrig_tasks_advancedChoiceWorld` such that reward amounts are parametrized for each side rather than being the same across all correct trials? 

At the moment, the task_parameters list REWARD_AMOUNT_UL as a single parameter. In _base_choice_world.py_ the method to set the reward amount is defined in the class _ChoiceWorldSession_
```
def reward_amount(self):
        return self.task_params.REWARD_AMOUNT_UL
```
which simply calls the parameter and is not conditional on anything else. Is this something that we could overload somehow, so it calls one of two different amounts depending on the current trial?

**Comment by oliche** [comment]
So we decided to go for a parametrisation for each contingency (combination of contrast and position)

Implementation is part of 8.19.0 release
59474f0131b799a24bdd4f46d517f489a338101c
iblrig/iblrig_tasks/_iblrig_tasks_advancedChoiceWorld/task_parameters.yaml
