### ISSUE TITLE
Ephys Choice world is extracting with the wrong pre-defined sequence on V8

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblrig#658]
1. There is no reason to extract those differently than other sessions: fix the extraction code
2. Make sure the pre-defined sessions are used in V8

**Comment by oliche** [comment]
Re-assign the extraction of ephys CW to the generic biased CW

**Comment by mayofaulkner** [comment]
Fixed and merged with https://github.com/int-brain-lab/ibllib/pull/789
