### ISSUE TITLE
clarify if changes to task_settings.py have to be made in iblrig or iblrig_params folder

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#68]
right now, when changing settings we're doing it in both files, which is very confusing to the user

**Comment by nbonacchi** [comment]
As a general rule code, data, and parameters should be kept separate. Data is what you probably want to backup and run analyses on, code is what you want to update and run, and parameters change from install to install.
Unfortunately, and contrary to this statement, PyBpod requires the task code and the data to be in its parameter/project folder. To work around this besides the iblrig folder where all the code lives, we have the iblrig_data folder for, well, data and the iblrig_params folder where on install I copy the code to the location PyBpod expects it to be. So everything in iblrig/tasks is copied to the appropriate locations and will be running from there. 
Short answer: python code changes (of task_settings.py files) only in the iblrig_params folder. If you use the pybpod editor that's the file that changes.

Every update I squash these changes and copy the new task code files in the params folder again so these changes are volatile.

**Comment by anne-urai** [comment]
Ok so if I understand correctly, if we want to change any settings it should be in `iblrig_params` NOT `iblrig`. If that's true, can you add it to the instructions (e.g. where to add COMports etc)?

**Comment by GaelleChapuis** [comment]
I added it as a note onto the user guides under State machine setup.
