### ISSUE TITLE
Tare Water Calibration

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#70]
_iblrig_calibration_water does not tare the scale at the beginning. You have to do this manually at the start. Could this be incorporated into the code?

**Comment by anne-urai** [comment]
I don't believe it's necessary, since the code always takes the difference before and after delivering drops

**Comment by anne-urai** [comment]
In https://github.com/int-brain-lab/iblrig/blob/master/tasks/_iblrig_calibration_water/_iblrig_calibration_water.py

change line 152 
```
stopweight = 0  # can ask user if scale not tared
```

to
```
stopweight = scale_read(sph.OAHUS_SCALE_PORT)
```
