### ISSUE TITLE
iblrigv8: check ephysChoiceWorld overwrite of pre-generated trial data

### ISSUE THREAD

**Issue by davcrom** [int-brain-lab/iblrig#707]
@bimac just a reminder of the potential bug we found yesterday.

It seems that the `_iblrig_tasks_ephysChoiceWorld.Session` class may be overwriting trial data loaded from the pre-generated fixtures .pqt file. Haven't had a chance to test this is in fact the case, but seems worth it to double-check.

The class inherits the `next_trial()` method from `BiasedChoiceWorldSession`, which calls `draw_next_tirial_info(pleft=pleft)` without kwargs specifying the pre-defined position and contrast. With the default values as `None` these kwargs appear to get overwritten by a random draw on each trial.

Maybe the intended functionality is only to maintain the pre-generated block structure, in which case passing `pleft` is fine... Something to think about!

**Comment by bimac** [comment]
Good catch @davcrom! Yes, it was in fact overwriting the `trials_table`. A fix will come with the next release (#711, ready for testing on branch [iblrigv8dev](/int-brain-lab/iblrig/tree/iblrigv8dev))
