### ISSUE TITLE
When getting subjects possibility to say 'no to all' when asked to overwrite local data

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblrig#73]
When syncing to Alyx and pressing 'Get subjects' you get prompted whether to overwrite a subject which already exists locally. If you have many subjects you have to click through a whole bunch of prompts. Including the possibility to say 'No to all' and/or 'Yes to all' would be nice

**Comment by MicBoucinha** [comment]
This feature will be released in the next PyBpod version. No estimate right now when that will be though. It is already implemented in the 'develop' branch of the pybpod-alyx-module.
