### ISSUE TITLE
Training status retrieval does not seem to be working

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#738]
'No jsonable found' error message thrown when trying to impute training status from GUI, even though the jsonable exists (see print screen below).

Noticed in iblrigv8.24.7, on IBL-MESO-STIM, but this issue may have been around for some time as I haven't tried to use this feature in a while.

![image](https://github.com/user-attachments/assets/d922cf80-bea2-433d-8cf3-8a5042a2d7e0)

**Comment by oliche** [comment]
In the error message, it seems the path is with forward slashes, while the path shown in the file explorer is with backslashes

**Comment by bimac** [comment]
The UI of this feature is a bit clunky - you need to select the session path (the numbered folder - `001` in this case), not the `raw_task_data_xx` folder. Also note, that this feature was implemented for getting the training status for V7 sessions - V8 sessions will be dealt with automatically. Please let us know if this resolves the issue.

**Comment by samupicard** [comment]
I also tried selecting the session folder and the same error message was thrown. But if it's specific to v8 that might explain it. Is there a way to see the imputed training status in v8 for v8 sessions, before running the task itself? As we manually moved the mouse up a phase on Friday, I wasn't sure the automatic training status would be correct so I wanted to check. I then decided to manually select training phase 2, which worked fine, but the task performance GUI then showed "phase 1" in the title. This may have been because that was the automatically imputed one? Anyway, these conflicts can be a bit confusing so it would be good to streamline it somehow.

**Comment by samupicard** [comment]
It's also worth mentioning that many of our mice have multiple raw_task_data_xx folders in a session, and the latter ones are usually passiveChoiceWorld (which do not contain a .jsonable file). This might throw off the automatic training status computation?

**Comment by bimac** [comment]
> I also tried selecting the session folder and the same error message was thrown. But if it's specific to v8 that might explain it. 

Yes, I'm afraid it won't work for V8 sessions at all (it's looking for a `raw_behavior_data` sub-folder which does not exist in V8 sessions).

> Is there a way to see the imputed training status in v8 for v8 sessions, before running the task itself? As we manually moved the mouse up a phase on Friday, I wasn't sure the automatic training status would be correct so I wanted to check.

The values shown for the 'automatic' selection correspond to the computed values (or the default values if no previous session could be determined). 
![image](https://github.com/user-attachments/assets/c6e21705-a918-4cdc-8cf6-e4a2ab9c0ee6)

> I then decided to manually select training phase 2, which worked fine, but the task performance GUI then showed "phase 1" in the title. This may have been because that was the automatically imputed one?

I'll have a look at that, thanks for reporting.

> Anyway, these conflicts can be a bit confusing so it would be good to streamline it somehow.

Agreed. I'll try to make this clearer.

**Comment by bimac** [comment]
- the next release will have a renamed menu entry for the "get training phase" tool clarifying its intended use with V7 sessions
- the online plots indeed show the wrong training status (the correct training status, however, is being used). I'm working on a replacement for the online plots that will show the correct training status.
