### ISSUE TITLE
Implement 0% contrast probability is half than anything els in final contrast set

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#74]
https://docs.google.com/document/d/1d6mCpjvNf5KF0WcxaHmRS4_ghNHu3xJC0wx-I8prbr0/edit?ts=5c40a06d#

"**The probability of drawing a 0% stimulus is half that of any other.**" ([Behavioural task - Habituation and Training](https://docs.google.com/document/d/1d6mCpjvNf5KF0WcxaHmRS4_ghNHu3xJC0wx-I8prbr0/edit?ts=5c40a06d#))

(n-1)p + 0.5p = 1

Final contrast set
c_set = [1, 0.25, 0.125, 0.0625, 0] 
len(c_set) = 5
...
4p + 0.5p = 1
p = 1/4,5 = 0.2222

cset_prob = [0.2222, 0.2222, 0.2222, 0.2222, 0.1112]

on next trial in contrast object. If contrast_set is final i.e len == 5 and "0" in contrast_set
np.random.choice(self.contrast_set, p=[0.2222, 0.2222, 0.2222, 0.2222, 0.1112])

**Comment by nbonacchi** [comment]
@k1o0 (assuming you are miles)
This is only in the case the animal has reached the full contrast set and removed the 50% contrast right?

**Comment by k1o0** [comment]
No this should be the case as soon as the zero contrast is introduced

**Comment by nbonacchi** [comment]
Cool that is simpler to check for:
So given that p in the above eq. is always 1 over length of the set - 1:
n_1 = len(self.contrast_set) - 1
z = n_1 + 0.5
p = [1/z] * (n_1 + 1)  # creates a list of n-1+1 values
p[-1] *= 0.5  # last value should be half
this should work for all lengths 
and I use it if 0 in contrast_set....

**Comment by k1o0** [comment]
This came up again in the behaviour working group as one mouse is taking time to get used to the low contrast trials.  Let us know when the code changes have taken effect.

**Comment by nbonacchi** [comment]
It's done, just waiting for some other things to be done to merge to master...
Should I rush the merge?

**Comment by k1o0** [comment]
Yeah I think cherry-picking the commit into master would be good
