### ISSUE TITLE
Plotting data ‘online’ (at each trial) for input/output as debugger (oscilloscope) mode

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#77]
To help user in debugging their rig, it would be nice to have an extra plot that would show the TTL states of each I/O during that trial.

**Comment by nbonacchi** [comment]
This is related to #66

**Comment by GaelleChapuis** [comment]
Can this be implemented?

We just tried something at Berkeley: we remove the frame2TTL sensor from the screen, and we received **no error feedback message** - as if the rig was working!

It would greatly help to be able to visualize the incoming data on a plot instead on solely relying on error messages !

**Comment by GaelleChapuis** [comment]
The plot can be done offline, it does not need to be online plot, if it helps the implementation.
