### ISSUE TITLE
automatically save project

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#79]
before running or stopping a task, automatically save so that the user won't have to do this manually each time

**Comment by GaelleChapuis** [comment]
I actually do not understand fully the reason why we have to save a project each time? what is saved exactly?

**Comment by nbonacchi** [comment]
Things you go in the GUI have side effects:
e.g. deleting a user o subject will immediately delete it from the GUI. However, to each element of the GUI corresponds a folder a file or a line in a file that is stored in iblrig_params/IBL. 
Clicking save 'implements' those changes, meaning in the example above, the corresponding files will be deleted only when you click save...
The check to see if anything has changed is a hash computed on the projects folder (iblrig_params/IBL) so even if you set a value to the same value there will be a change and the project requires to be saved before running.
This is a PyBpod enhancement/proposal and should be submitted to the pybpod repo.
I can do that periodically and create a tak to forward issues to the pybpod repo. However the timing of release for the main PyBpod project is not just up to me...

**Comment by anne-urai** [comment]
ok do you want to open an issue with them? you can probably better describe the problem

**Comment by MicBoucinha** [comment]
In the next version of PyBpod, a new configuration option will allow to auto save the project. 

This auto save happens only right before a new run will happen and not before. This allows to exit the application without saving the data from the last run if that is what is desired. Exiting the application will always ask to the save the projects in case they aren't saved.
