### ISSUE TITLE
sync to alyx

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#81]
when 'getting subjects' from alyx, it looks like all mice associated with the specific lab (i.e. cshl) are loaded. This is great, although also some dead mice are included - could the user get a prompt for which mice to sync, or can dead mice automatically disappear from the subjects list?

**Comment by nbonacchi** [comment]
It should get only the subjects of the logged in user, not the whole lab/institution.

Regarding not getting dead animals, this is probably a good idea, I'll fw: it

**Comment by anne-urai** [comment]
request: for institutions where multiple people train mice, *all* animals should be synced - e.g. sometimes I want to run a mouse that's under valeria's name, or vice versa. Right now that seems tricky

**Comment by MicBoucinha** [comment]
Regarding the dead mice being removed automatically, right now PyBpod will continue to ask for deletion confirmation from the user. I am working on a solution to not ask it and perhaps after the import of subject, present a list of all the mice that were removed because they were dead.

**Comment by MicBoucinha** [comment]
When getting subjects from alyx, the deletion confirmation dialog for the dead mice won't appear anymore. If a subject is deleted from the tree manually the confirmation dialog continues to show up. These features will be available in the next PyBpod version.
