### ISSUE TITLE
ask for COMport in water calibration task

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#88]
Just like trainingChoiceWorld asks for the rotary encoder and frame2ttl comports

**Comment by nbonacchi** [comment]
Can you elaborate?

**Comment by anne-urai** [comment]
when running trainingChoiceWorld, a dialog box asks for the COMport of the rotary encoder and frame2TTL (rather than the user having to enter this in `task_settings.py`. The same should happen with the COMport of the scale when running the water calibration task, so that the user doesn't have to go into the `task_settings.py` file there either. 

this would be especially helpful given that there is a lot of confusion about having to change settings in `iblrig_params` while changes in `iblrig` do nothing.

**Comment by nbonacchi** [comment]
The scale is mobile and not fixed, meaning the probability of it changing COM port is higher than the Bpod modules that should stay always connected.

**Comment by anne-urai** [comment]
Then it should be asked each time - now the user has to deduce by themselves that they should go into `iblrig_params/tasks/water_calibration/task_settings.py` each time...

**Comment by nbonacchi** [comment]
or you can double click on the task you are trying to run in pybpod and select task_settings.py and change it there
