### ISSUE TITLE
ask mouse weight before and after task

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#93]
Can then compare with water delivery to ensure the animal ingested the water. 

Also ask (after stopping session): fecal count - tbd how this will be saved in Alyx

**Comment by nbonacchi** [comment]
I'm not very fond of this proposal, shouldn't it go to the mice training WG? @GaelleChapuis

**Comment by GaelleChapuis** [comment]
I will put it onto the agenda for next week (the two points):

- asking for weight after task
- asking for poop count before or after task

**Comment by GaelleChapuis** [comment]
So, it was decided that we do NOT want to ask weight after the task.

For poop counting however, it would be useful to have a pop up window (that would go into the JSON field), to pop up at the END of the session.
