### ISSUE TITLE
redundant/irrelevant variable?

### ISSUE THREAD

**Issue by HernandoMV** [int-brain-lab/iblrig#97]
Hi Nicco, in task_parameter file, is this line relevant? It is confusing:

# ROTARY ENCODER
ROTARY_ENCODER_PORT = 'COM5'

I assume it is not used and overriden by the .bpod_comports.json file?

**Comment by nbonacchi** [comment]
which task?

**Comment by HernandoMV** [comment]
calibration_water

**Comment by nbonacchi** [comment]
I think it's the same problem as other issue:
please update to 3.5.3

the only contents now ot task_Setting of the water calibration ar the following:
```
IBLRIG_FOLDER = "C:\\iblrig"
IBLRIG_DATA_FOLDER = None  # If None will be ..\\iblrig_data from IBLRIG_FOLDER
OAHUS_SCALE_PORT = None  # 'COM2'  # Set to None for manual weight logging

MIN_OPEN_TIME = 50  # (ms)
MAX_OPEN_TIME = 201  # (ms)
STEP = 50  # (ms)
PASSES = 3  # number of times to repeat the same open_time per run

NTRIALS = 100  # number of drops per open time to average across
IPI = 0.1  # (s) Inter Pulse Interval
```
