### ISSUE TITLE
Clicking on stop task from mouse run task interface relaunches task 

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#98]
Currently there are 2 ways of running a task:
1: select setup name under experiments, add subjects et al. run.
(this method works fine)
2: select a Subject and right click to run on setup:
running works fine (I think) but when clicking stop the task is stopped and immeditely restarted.
Either there is a second call from the stop button to session.run or, more probable, there is a double run call on start and one process hangs until the first one stops. I say this because the behavior using stop AND sto trial is exactly the same...

**Comment by MicBoucinha** [comment]
This is fixed and will be part of PyBpod in the next release. Currently in the develop branch of pybpod-gui-api.
